Repository microsoft/demikernel, pull requests merged in 2022-11, with the labels that each got.

#320 [demikernel] Integrate `DemiBuffer` into the System as `Buffer`/`DataBuffer` Replacement
  src/rust/catcollar/futures/pop.rs
  src/rust/catcollar/iouring.rs
  src/rust/catcollar/mod.rs
  src/rust/catcollar/runtime/memory.rs
  src/rust/catcollar/runtime/mod.rs
  src/rust/catcollar/runtime/network.rs
  src/rust/catnap/futures/pop.rs
  src/rust/catnap/futures/push.rs
  src/rust/catnap/futures/pushto.rs
  src/rust/catnap/runtime.rs
  src/rust/catnapw/futures/push.rs
  src/rust/catnapw/futures/pushto.rs
  src/rust/catnip/runtime/memory/manager.rs
  src/rust/catnip/runtime/memory/mempool.rs
  src/rust/catnip/runtime/memory/mod.rs
  src/rust/catnip/runtime/network.rs
  src/rust/catpowder/runtime/memory.rs
  src/rust/catpowder/runtime/network.rs
  src/rust/inetstack/mod.rs
  src/rust/inetstack/operations.rs
  src/rust/inetstack/protocols/arp/packet/header.rs
  src/rust/inetstack/protocols/arp/packet/message.rs
  src/rust/inetstack/protocols/arp/peer.rs
  src/rust/inetstack/protocols/ethernet2/frame.rs
  src/rust/inetstack/protocols/icmpv4/datagram/header.rs
  src/rust/inetstack/protocols/icmpv4/datagram/message.rs
  src/rust/inetstack/protocols/icmpv4/peer.rs
  src/rust/inetstack/protocols/ipv4/datagram.rs
  src/rust/inetstack/protocols/ipv4/tests.rs
  src/rust/inetstack/protocols/peer.rs
  src/rust/inetstack/protocols/tcp/established/background/sender.rs
  src/rust/inetstack/protocols/tcp/established/ctrlblk.rs
  src/rust/inetstack/protocols/tcp/established/mod.rs
  src/rust/inetstack/protocols/tcp/established/sender.rs
  src/rust/inetstack/protocols/tcp/operations.rs
  src/rust/inetstack/protocols/tcp/peer.rs
  src/rust/inetstack/protocols/tcp/segment.rs
  src/rust/inetstack/protocols/tcp/tests/established.rs
  src/rust/inetstack/protocols/tcp/tests/mod.rs
  src/rust/inetstack/protocols/tcp/tests/setup.rs
  src/rust/inetstack/protocols/udp/datagram/header.rs
  src/rust/inetstack/protocols/udp/datagram/mod.rs
  src/rust/inetstack/protocols/udp/futures/pop.rs
  src/rust/inetstack/protocols/udp/peer.rs
  src/rust/inetstack/protocols/udp/tests.rs
  src/rust/inetstack/test_helpers/engine.rs
  src/rust/inetstack/test_helpers/runtime.rs
  src/rust/runtime/memory/buffer/demibuffer.rs
  src/rust/runtime/memory/mod.rs
  src/rust/runtime/network/consts.rs
  src/rust/runtime/network/mod.rs
  src/rust/runtime/types/memory.rs
  tests/rust/common/libos.rs
  tests/rust/common/runtime.rs
  tests/rust/tcp.rs
  tests/rust/udp.rs
Labels: enhancement

#327 [catnip] Missing Check for Return Value of `rte_eal_init()`
  src/rust/catnip/runtime/mod.rs
Labels: bug

#331 [catnip] Wrong MTU Initialization
  src/rust/catnip/runtime/mod.rs
Labels: bug

#336 [pdpix] Use trace Logging Level to Propagate Unexpected Conditions
  src/rust/demikernel/bindings.rs
  src/rust/demikernel/libos/mod.rs
Labels: enhancement

#338 [examples] Support Multiple Clients in `tcp-echo`
  examples/rust/tcp-echo.rs
Labels: enhancement

#339 [arp] Add Remove Function
  src/rust/inetstack/collections/hashttlcache/mod.rs
  src/rust/inetstack/collections/hashttlcache/tests.rs
Labels: enhancement

#343 [examples] Multi-Client Support for `tcp-dump`
  examples/rust/tcp-dump.rs
  examples/rust/tcp-echo.rs
Labels: bug, enhancement
