Repository microsoft/demikernel, pull requests merged in 2022-12, with the labels that each got.

#351 [inetstack] Accept Ethernet Multicast Packets
  src/rust/inetstack/mod.rs
Labels: bug

#342 [tools] Initial `demikernel-ci`
  testsys/build.sh
  testsys/jobs/checkout.py
  testsys/jobs/cleanup.py
  testsys/jobs/compile.py
  testsys/jobs/launch.py
  testsys/test.sh
  tools/demikernel-ci.py
Labels: feature

#360 [ci] Updating Catnap Workflow
  .github/workflows/catnap.yml
Labels: enhancement

#361 [ci] Updating Catpowder Workflow
  .github/workflows/catpowder.yml
Labels: enhancement

#362 [ci] Updating Catcollar Workflow
  .github/workflows/catcollar.yml
Labels: enhancement

#352 [catnip] Use PAL in Catnip
  examples/rust/udp-echo.rs
  src/rust/catnip/interop.rs
  src/rust/pal/functions.rs
Labels: enhancement

#365 [ci] Checkout to Dev Branch
  .github/workflows/cleanup.yml
  .github/workflows/setup.yml
Labels: bug

#358 [doc] Testing Instructions
  README.md
  doc/testing.md
  man/demi_wait.md
Labels: documentation

#370 [inetstack] Push Empty Buffer on FIN
  src/rust/inetstack/protocols/tcp/established/ctrlblk.rs
Labels: bug

#375 [build] Bumping DPDK Version
  .github/workflows/catnip.yml
  Cargo.toml
  scripts/config/azure.yaml
  scripts/config/default.yaml
  scripts/setup/dpdk.sh
  src/rust/catnip/runtime/mod.rs
Labels: enhancement

#378 [catnapw] Use `DemiBuffer` Instead of `Buffer`/`DataBuffer`
  src/rust/catnapw/futures/pop.rs
  src/rust/catnapw/mod.rs
  src/rust/catnapw/runtime.rs
Labels: bug

#374 [tcp] Fix Retransmit and Cleanup Retransmission Timeout Calculator
  Cargo.toml
  src/rust/inetstack/protocols/tcp/established/background/retransmitter.rs
  src/rust/inetstack/protocols/tcp/established/background/sender.rs
  src/rust/inetstack/protocols/tcp/established/ctrlblk.rs
  src/rust/inetstack/protocols/tcp/established/mod.rs
  src/rust/inetstack/protocols/tcp/established/rto.rs
  src/rust/inetstack/protocols/tcp/established/sender.rs
Labels: bug

#373 [test] Missing to Run Some Unit Tests in `test-unit-rust` Target
  linux.mk
  windows.mk
Labels: bug

#383 [tools] Several Improvements for `demikernel-ci`
  doc/testing.md
  tools/demikernel-ci.py
Labels: bug, enhancement

#389 [ci] Initial Integration of Catnapw with Regression System
  .github/workflows/catnapw.yml
  doc/building-windows.md
  windows.mk
Labels: bug, enhancement, documentation
