Repository microsoft/demikernel, pull requests merged in 2022-10, with the labels that each got.

#291 [collections] Shared Ring Buffer Abstraction
  src/rust/collections/mod.rs
  src/rust/collections/ring.rs
  src/rust/collections/shared_ring.rs
  src/rust/pal/linux/shm.rs
Labels: feature

#294 [runtime] Offset Identifiers of I/O Queue Descriptors
  src/rust/runtime/queue/mod.rs
Labels: enhancement

#296 [pdpix] Tagging Deprecated System Calls
  src/rust/catcollar/mod.rs
  src/rust/catnap/mod.rs
  src/rust/demikernel/libos/mod.rs
  src/rust/demikernel/libos/network.rs
Labels: bug

#300 [catnip] Bug Fix: Don't Trim on SGA Clone
  src/rust/catnip/runtime/memory/manager.rs
  src/rust/runtime/memory/buffer/dpdkbuffer.rs
Labels: bug

#302 [pdpix] Wrong Conversions Between `DataBuffer` and `demi_sgarray_t`
  src/rust/catcollar/runtime/memory.rs
  src/rust/catnap/runtime.rs
  src/rust/catnip/runtime/memory/manager.rs
  src/rust/catpowder/runtime/memory.rs
  src/rust/lib.rs
  src/rust/runtime/memory/buffer/databuffer.rs
Labels: bug

#303 [examples] Use PDPIX In Rust Examples
  examples/rust/tcp-dump.rs
  examples/rust/tcp-echo.rs
  examples/rust/tcp-ping-pong.rs
  examples/rust/tcp-pktgen.rs
  examples/rust/tcp-push-pop.rs
  examples/rust/udp-dump.rs
  examples/rust/udp-echo.rs
  examples/rust/udp-ping-pong.rs
  examples/rust/udp-pktgen.rs
  examples/rust/udp-push-pop.rs
  examples/rust/udp-relay.rs
Labels: enhancement

#304 [pdpix] Drop Deprecated System Calls
  src/rust/catcollar/mod.rs
  src/rust/catnap/mod.rs
  src/rust/catnip/mod.rs
  src/rust/catpowder/mod.rs
  src/rust/demikernel/libos/mod.rs
  src/rust/demikernel/libos/network.rs
  src/rust/inetstack/mod.rs
Labels: enhancement

#307 [pdpix] Generic `wait()`
  src/rust/catcollar/mod.rs
  src/rust/catnap/mod.rs
  src/rust/catnip/mod.rs
  src/rust/catpowder/mod.rs
  src/rust/demikernel/libos/network.rs
Labels: enhancement

#305 [winport] Platform Abstraction Layer for Network
  examples/rust/tcp-dump.rs
  examples/rust/tcp-echo.rs
  examples/rust/tcp-ping-pong.rs
  examples/rust/tcp-pktgen.rs
  examples/rust/tcp-push-pop.rs
  examples/rust/udp-dump.rs
  examples/rust/udp-echo.rs
  examples/rust/udp-ping-pong.rs
  examples/rust/udp-pktgen.rs
  examples/rust/udp-push-pop.rs
  examples/rust/udp-relay.rs
  examples/rust/windows.mk
  src/rust/catcollar/mod.rs
  src/rust/catnap/mod.rs
  src/rust/demikernel/bindings.rs
  src/rust/inetstack/mod.rs
  src/rust/pal/constants.rs
  src/rust/pal/data_structures.rs
  src/rust/pal/functions.rs
  src/rust/pal/mod.rs
  src/rust/runtime/types/memory.rs
  tests/rust/tcp.rs
  tests/rust/udp.rs
Labels: enhancement

#298 [runtime] DemiBuffer Abstraction
  src/rust/lib.rs
  src/rust/pal/arch.rs
  src/rust/pal/mod.rs
  src/rust/runtime/memory/buffer/demibuffer.rs
  src/rust/runtime/memory/buffer/mod.rs
Labels: enhancement

#311 [test] Disable `DemiBuffer` UnitTest
  src/rust/runtime/memory/buffer/demibuffer.rs
Labels: bug

#312 [runtime] Bad Deref in `DemiBuffer::drop()` Causes Segmentation Fault
  src/rust/runtime/memory/buffer/demibuffer.rs
Labels: bug

#313 [pdpix] Generic `wait()`, `wait_any()` and `timedwait()`
  src/rust/catcollar/mod.rs
  src/rust/catnap/mod.rs
  src/rust/catnip/mod.rs
  src/rust/catpowder/mod.rs
  src/rust/demikernel/libos/mod.rs
  src/rust/demikernel/libos/network.rs
  src/rust/inetstack/mod.rs
Labels: enhancement
