Repository microsoft/demikernel, pull requests merged in 2022-09, with the labels that each got.

#159 [pdpix] Build Composition of LibOSes
  .github/workflows/catcollar.yml
  .github/workflows/catnap.yml
  .github/workflows/catnip.yml
  .github/workflows/catpowder.yml
  Cargo.toml
  examples/rust/tcp-ping-pong.rs
  examples/rust/tcp-push-pop.rs
  examples/rust/udp-ping-pong.rs
  examples/rust/udp-push-pop.rs
  src/rust/catcollar/futures/mod.rs
  src/rust/catcollar/mod.rs
  src/rust/catcollar/runtime/memory.rs
  src/rust/catnap/futures/mod.rs
  src/rust/catnap/mod.rs
  src/rust/catnap/runtime.rs
  src/rust/catpowder/runtime/memory.rs
  src/rust/demikernel/bindings.rs
  src/rust/demikernel/libos/mod.rs
  src/rust/demikernel/libos/name.rs
  src/rust/demikernel/libos/network.rs
  src/rust/lib.rs
  tests/rust/sga.rs
Labels: feature

#164 [doc] `demi_socket()` Manual Page
  man/demi_socket.md
Labels: documentation

#270 [doc] Cleaning Up PDPIX API Documentation
  doc/syscalls.md
  include/demi/libos.h
  include/demi/sga.h
  include/demi/types.h
  include/demi/wait.h
  man/demi_accept.md
  man/demi_bind.md
  man/demi_connect.md
  man/demi_listen.md
  man/demi_pop.md
  man/demi_push.md
  man/demi_pushto.md
  man/demi_sgaalloc.md
  man/demi_socket.md
  man/demi_wait.md
  tests/c/syscalls.c
Labels: documentation

#271 [examples] TCP and UDP Examples for Rust
  Cargo.toml
  examples/rust/Makefile
  examples/rust/tcp-dump.rs
  examples/rust/tcp-echo.rs
  examples/rust/tcp-pktgen.rs
  examples/rust/udp-dump.rs
  examples/rust/udp-echo.rs
  examples/rust/udp-pktgen.rs
  examples/rust/udp-relay.rs
Labels: feature

#273 [build] Split makefiles for OS
  Makefile
  examples/c/Makefile
  examples/c/linux.mk
  examples/c/windows.mk
  examples/rust/Makefile
  examples/rust/linux.mk
  examples/rust/windows.mk
  linux.mk
  tests/Makefile
  tests/c/Makefile
  tests/c/linux.mk
  tests/c/windows.mk
  tests/linux.mk
  tests/windows.mk
  windows.mk
Labels: enhancement

#276 [build] No Hardcode Default Path for `CARGO`
  Makefile
  linux.mk
Labels: bug

#277 [pdpix] `timedwait()` System Call
  include/demi/wait.h
  man/demi_wait.md
  src/rust/catcollar/mod.rs
  src/rust/catnap/mod.rs
  src/rust/catnip/mod.rs
  src/rust/catpowder/mod.rs
  src/rust/demikernel/bindings.rs
  src/rust/demikernel/libos/mod.rs
  src/rust/demikernel/libos/network.rs
  src/rust/inetstack/mod.rs
  tests/c/Makefile
  tests/c/linux.mk
  tests/c/syscalls.c
Labels: feature

#280 [pdpix] Global State for Demikernel
  src/rust/demikernel/bindings.rs
Labels: bug, enhancement

#283 [catnap][catcollar] `demi_socket()` Fails with `EADDRINUSE`
  src/rust/catcollar/futures/accept.rs
  src/rust/catcollar/mod.rs
  src/rust/catnap/futures/accept.rs
  src/rust/catnap/mod.rs
  src/rust/lib.rs
  src/rust/pal/linux.rs
  src/rust/pal/mod.rs
Labels: bug

#286 [pal] Shared Memory Region Abstraction
  src/rust/pal/linux/mod.rs
  src/rust/pal/linux/shm.rs
Labels: feature

#289 [collections] Ring Buffer Abstraction
  src/rust/collections/mod.rs
  src/rust/collections/ring.rs
  src/rust/lib.rs
Labels: feature
