Repository microsoft/demikernel, pull requests merged in 2022-03, with the labels that each got.

#48 Update readme to point to SOSP paper
  README.md
Labels: documentation

#49 [doc] Fix Typo on Run Instructions
  README.md
Labels: documentation

#52 [contrib] Updating Contrib
  Cargo.toml
  src/catnap/mod.rs
  src/catnap/runtime.rs
  src/catnip/runtime/memory/manager.rs
  src/catnip/runtime/memory/mod.rs
  src/catpowder/runtime/memory.rs
  src/demikernel/libos.rs
  src/lib.rs
Labels: bug, confirmed

#55 [demikernel] Uniform `OperationResult` Across LibOSes
  src/catnap/futures/mod.rs
  src/catnap/mod.rs
Labels: bug
