Repository microsoft/demikernel, pull requests merged in 2023-08, with the labels that each got.

#861 [ci] No Concurrency for Catloop LibOS
  tools/ci/config/ci_map.yaml
Labels: bug

#853 [catmem] Restructuring
  doc/diagrams/Demikernel - Architecture.pdf
  doc/diagrams/Demikernel - Architecture.vsdx
  examples/rust/pipe-ping-pong.rs
  src/rust/catloop/duplex_pipe.rs
  src/rust/catmem/futures/close.rs
  src/rust/catmem/futures/mod.rs
  src/rust/catmem/futures/pop.rs
  src/rust/catmem/futures/push.rs
  src/rust/catmem/mod.rs
  src/rust/catmem/pipe.rs
  src/rust/catmem/queue.rs
  src/rust/catmem/ring/mod.rs
  src/rust/catmem/ring/pop_ring.rs
  src/rust/catmem/ring/push_ring.rs
  src/rust/demikernel/libos/memory.rs
  src/rust/demikernel/libos/mod.rs
  src/rust/runtime/network/mod.rs
  src/rust/runtime/network/ring/mod.rs
  src/rust/runtime/network/ring/operation.rs
  src/rust/runtime/network/ring/state.rs
Labels: enhancement

#857 [catnap] Move states and YielderHandle allocation into CatnapQueue
  Cargo.toml
  doc/diagrams/Demikernel - Architecture.pdf
  doc/diagrams/Demikernel - Architecture.vsdx
  src/rust/catnap/mod.rs
  src/rust/catnap/queue.rs
Labels: enhancement

#864 [catmem] Mutex locking
  doc/diagrams/Demikernel - Architecture.pdf
  doc/diagrams/Demikernel - Architecture.vsdx
  src/rust/catmem/ring/pop_ring.rs
  src/rust/catmem/ring/push_ring.rs
  src/rust/scheduler/mod.rs
  src/rust/scheduler/mutex.rs
Labels: bug, enhancement

#871 [examples] Handle `ECANCELED`
  examples/tcp-echo/server.rs
Labels: bug

#867 [catnap] Encapsulate scheduler in runtime
  src/rust/catnap/mod.rs
  src/rust/catnap/runtime.rs
Labels: enhancement

#868 [runtime] Move scheduler to shared runtime
  src/rust/catnap/mod.rs
  src/rust/catnap/runtime.rs
  src/rust/demikernel/libos/mod.rs
  src/rust/runtime/mod.rs
Labels: enhancement

#874 [contrib] Updating Dependencies
  Cargo.toml
Labels: enhancement

#876 [catmem] Move to catnap arch
  src/rust/catmem/mod.rs
  src/rust/catmem/queue.rs
  src/rust/catmem/ring/mod.rs
Labels: enhancement

#879 [catloop] Unify Scheduler
  src/rust/catloop/futures/mod.rs
  src/rust/catloop/mod.rs
Labels: enhancement

#880 [catloop] Remove Harvest on Close
  src/rust/catloop/mod.rs
Labels: enhancement

#893 [catloop] `INADDR_ANY` Should Be Supported As The Wildcard Address
  src/rust/catloop/mod.rs
Labels: bug

#897 [catnap] Move coroutines to standalone functions
  src/rust/catnap/mod.rs
Labels: enhancement

#904 [catnap] Don't Panic on Drop
  src/rust/catnap/mod.rs
  src/rust/runtime/mod.rs
Labels: enhancement

#899 [catloop] Interpose Error on Connect
  src/rust/catloop/socket.rs
Labels: bug

#900 [catloop] Disallow Bind to Non-Local Address
  src/rust/catloop/mod.rs
  src/rust/demikernel/config.rs
  src/rust/demikernel/libos/mod.rs
Labels: bug

#901 [catloop] Don't Allow `accept()` On A Socket That Is Already Accepting
  src/rust/catloop/mod.rs
  src/rust/catloop/queue.rs
Labels: bug

#902 [catnap] Moving to Standalone Async Functions
  src/rust/catnap/queue.rs
  src/rust/catnap/socket.rs
  src/rust/runtime/network/socket/state.rs
  tests/rust/tcp-test/wait/mod.rs
Labels: enhancement

#913 [test] Enable Integration Tests for Catloop
  tests/rust/tcp-test/bind/mod.rs
  tests/rust/tcp-test/main.rs
  tools/demikernel_ci.py
Labels: bug, enhancement

#909 [catcollar] Move to async fns
  src/rust/catcollar/futures/accept.rs
  src/rust/catcollar/futures/close.rs
  src/rust/catcollar/futures/connect.rs
  src/rust/catcollar/futures/mod.rs
  src/rust/catcollar/futures/pop.rs
  src/rust/catcollar/futures/push.rs
  src/rust/catcollar/futures/pushto.rs
  src/rust/catcollar/mod.rs
  src/rust/catcollar/runtime/mod.rs
Labels: enhancement

#865 [collections] Concurrent Ring Buffer
  src/rust/catmem/ring.rs
  src/rust/collections/concurrent_ring.rs
  src/rust/collections/mod.rs
  src/rust/collections/ring.rs
  src/rust/collections/shared_ring.rs
Labels: bug, enhancement

#915 [ci] Updating testing.md file.
  doc/testing.md
Labels: documentation

#921 [contrib] Updating Dependencies
  Cargo.toml
Labels: enhancement

#918 [catnapw] Merge the Catnapw and Catnap LibOSes
  Cargo.toml
  README.md
  doc/testing.md
  examples/c/udp-ping-pong.c
  examples/c/udp-push-pop.c
  include/demi/types.h
  man/demi_init.md
  src/rust/catnap/mod.rs
  src/rust/catnap/queue.rs
  src/rust/catnap/socket.rs
  src/rust/catnapw/futures/accept.rs
  src/rust/catnapw/futures/connect.rs
  src/rust/catnapw/futures/mod.rs
  src/rust/catnapw/futures/pop.rs
  src/rust/catnapw/futures/push.rs
  src/rust/catnapw/futures/pushto.rs
  src/rust/catnapw/mod.rs
  src/rust/catnapw/runtime.rs
  src/rust/demikernel/bindings.rs
  src/rust/demikernel/libos/mod.rs
  src/rust/demikernel/libos/name.rs
  src/rust/demikernel/libos/network.rs
  src/rust/lib.rs
  src/rust/pal/constants.rs
  src/rust/pal/functions.rs
  tests/rust/tcp-test/listen/mod.rs
  tests/rust/tcp-test/socket/mod.rs
  windows.mk
Labels: enhancement

#917 [catmem] Use Full Ring Name
  src/rust/catmem/queue.rs
  src/rust/catmem/ring.rs
  src/rust/collections/concurrent_ring.rs
Labels: enhancement

#922 [contrib] Updating Rust Toolchain
  rust-toolchain
  src/rust/demikernel/bindings.rs
Labels: bug, enhancement
