Repository microsoft/demikernel, pull requests merged in 2023-07, with the labels that each got.

#809 [build] Wrong Build Dependencies
  linux.mk
Labels: bug

#802 [scheduler] Improve tests
  src/rust/scheduler/scheduler.rs
Labels: enhancement

#814 [build] Increase Build Timeout
  linux.mk
Labels: bug

#813 [build] Build Warnings
  src/rust/catnip/runtime/memory/mempool.rs
  src/rust/demikernel/libos/network.rs
Labels: bug

#811 [catloop] Inconsistent Port Allocation
  src/rust/catloop/mod.rs
Labels: bug

#810 [inetstack] Non Ephemeral Port May Get Released
  src/rust/catloop/mod.rs
  src/rust/inetstack/protocols/ip/ephemeral.rs
  src/rust/inetstack/protocols/tcp/peer.rs
  src/rust/inetstack/protocols/udp/peer.rs
Labels: bug

#817 [ci] Enable tcp-echo Catloop LibOS
  tools/demikernel_ci.py
Labels: enhancement

#819 [scheduler] Several scope, readability and test improvements
  src/rust/scheduler/scheduler.rs
Labels: enhancement

#815 [catloop] Drop Trait Implementation
  src/rust/catloop/mod.rs
Labels: bug

#836 [catloop] Always Bound Read from Control Duplex Pipe
  src/rust/catloop/futures/accept.rs
Labels: bug

#838 [scheduler] Avoid double remove()
  src/rust/scheduler/scheduler.rs
Labels: bug

#796 [ci] Improve CI configurability
  .gitignore
  tools/ci/config/ci_map.yaml
  tools/ci/src/base_test.py
  tools/ci/src/ci_map.py
  tools/ci/src/test_impls/pipe_open_test.py
  tools/ci/src/test_impls/pipe_ping_pong.py
  tools/ci/src/test_impls/pipe_push_pop.py
  tools/ci/src/test_impls/tcp_close_test.py
  tools/ci/src/test_impls/tcp_echo_test.py
  tools/ci/src/test_impls/tcp_ping_pong_test.py
  tools/ci/src/test_impls/tcp_push_pop_test.py
  tools/ci/src/test_impls/tcp_wait_test.py
  tools/ci/src/test_impls/udp_ping_pong_test.py
  tools/ci/src/test_impls/udp_push_pop_test.py
  tools/ci/src/test_instantiator.py
  tools/ci/unit_tests/test_callback_example.py
  tools/ci/unit_tests/test_ci_map.py
  tools/ci/unit_tests/test_data/ci_map.yaml
  tools/ci/unit_tests/test_data/scaffolding.yaml
  tools/ci/unit_tests/test_test_impls.py
  tools/ci/unit_tests/test_test_instantiator.py
  tools/demikernel_ci_new.py
Labels: enhancement

#844 [catnap] Enhancement: More compact state machine code
  src/rust/catnap/socket.rs
Labels: enhancement

#816 [catloop] Missing `async_close()`
  src/rust/catloop/duplex_pipe.rs
  src/rust/catloop/futures/mod.rs
  src/rust/catloop/mod.rs
  src/rust/demikernel/libos/network.rs
Labels: bug

#845 [ci] New workflow files
  .github/workflows/catcollar_new.yml
  .github/workflows/catloop_new.yml
  .github/workflows/catmem_new.yml
  .github/workflows/catnap_new.yml
  .github/workflows/catnapw_new.yml
  .github/workflows/catnip_new.yml
  .github/workflows/catpowder_new.yml
Labels: enhancement, feature

#850 [scheduler] Centralize index computations, simplify TaskHandle
  src/rust/scheduler/handle.rs
  src/rust/scheduler/scheduler.rs
Labels: enhancement

#855 [runtime] Enhancement: drain for IoQueueTable
  src/rust/runtime/queue/mod.rs
Labels: enhancement

#851 [catnap] Enhancement: re-architect Catnap
  doc/diagrams/Demikernel - Architecture.pdf
  doc/diagrams/Demikernel - Architecture.vsdx
  src/rust/catnap/coroutines/accept.rs
  src/rust/catnap/coroutines/close.rs
  src/rust/catnap/coroutines/connect.rs
  src/rust/catnap/coroutines/mod.rs
  src/rust/catnap/coroutines/pop.rs
  src/rust/catnap/coroutines/push.rs
  src/rust/catnap/mod.rs
  src/rust/catnap/queue.rs
  src/rust/catnap/socket.rs
  src/rust/runtime/network/mod.rs
  src/rust/runtime/network/socket/mod.rs
  src/rust/runtime/network/socket/operation.rs
  src/rust/runtime/network/socket/state.rs
Labels: enhancement

#854 [ci] Switch to new CI architecture
  .github/workflows/catcollar_new.yml
  .github/workflows/catloop_new.yml
  .github/workflows/catmem_new.yml
  .github/workflows/catnap_new.yml
  .github/workflows/catnapw_new.yml
  .github/workflows/catnip_new.yml
  .github/workflows/catpowder_new.yml
  tools/demikernel_ci.py
  tools/demikernel_ci_new.py
Labels: enhancement
