Repository microsoft/demikernel, pull requests merged in 2023-05, with the labels that each got.

#708 [test] Add drop function to tcp echo
  examples/tcp-echo/client.rs
  examples/tcp-echo/server.rs
Labels: enhancement

#706 [test] Add drop function to pipe-open
  examples/pipe-open/client.rs
  examples/pipe-open/server.rs
Labels: enhancement

#707 [test] Add drop function to tcp-close
  examples/tcp-close/client.rs
  examples/tcp-close/server.rs
Labels: enhancement

#709 [test] Add cleanup code to pipe system tests
  examples/rust/pipe-ping-pong.rs
  examples/rust/pipe-push-pop.rs
Labels: enhancement

#713 [test] Add cleanup to UDP system tests
  examples/rust/udp-dump.rs
  examples/rust/udp-echo.rs
  examples/rust/udp-ping-pong.rs
  examples/rust/udp-pktgen.rs
  examples/rust/udp-push-pop.rs
  examples/rust/udp-relay.rs
Labels: enhancement

#711 [runtime] Remove QResult
  src/rust/lib.rs
  src/rust/runtime/mod.rs
  src/rust/runtime/queue/mod.rs
  src/rust/runtime/queue/operation_result.rs
Labels: enhancement

#724 [catnap] Implement drop for cleanup on exit
  src/rust/catnap/mod.rs
Labels: bug

#722 [PDPIX] Do not reuse qtokens
  src/rust/catloop/duplex_pipe.rs
  src/rust/catnap/queue.rs
  src/rust/demikernel/libos/mod.rs
  src/rust/inetstack/mod.rs
  src/rust/scheduler/handle.rs
  src/rust/scheduler/scheduler.rs
Labels: bug

#726 [pdpix] Don't Optimize Size of Structures
  examples/pipe-open/server.rs
  examples/rust/pipe-ping-pong.rs
  examples/rust/pipe-push-pop.rs
  examples/rust/tcp-ping-pong.rs
  examples/rust/tcp-pktgen.rs
  examples/rust/tcp-push-pop.rs
  examples/rust/udp-echo.rs
  examples/rust/udp-ping-pong.rs
  examples/rust/udp-pktgen.rs
  examples/rust/udp-push-pop.rs
  examples/tcp-close/client.rs
  examples/tcp-close/server.rs
  examples/tcp-echo/client.rs
  examples/tcp-echo/server.rs
  examples/tcp-wait/client.rs
  examples/tcp-wait/server.rs
  include/demi/types.h
  src/rust/catcollar/mod.rs
  src/rust/catloop/mod.rs
  src/rust/catmem/mod.rs
  src/rust/catnap/mod.rs
  src/rust/catnip/interop.rs
  src/rust/catpowder/interop.rs
  src/rust/runtime/types/memory.rs
  src/rust/runtime/types/ops.rs
  tests/rust/pipe-test/async_close/mod.rs
  tests/rust/pipe-test/pop_wait/server.rs
  tests/rust/pipe-test/push_wait/client.rs
  tests/rust/pipe-test/push_wait/server.rs
  tests/rust/tcp-test/accept/mod.rs
  tests/rust/tcp-test/close/async_close.rs
  tests/rust/tcp-test/close/wait.rs
  tests/rust/tcp-test/connect/mod.rs
  tests/rust/tcp-test/listen/mod.rs
Labels: bug

#727 [runtime] Closing State for Sockets
  src/rust/catnap/mod.rs
  src/rust/catnap/socket.rs
Labels: bug

#732 [runtime] Make `RECEIVE_BATCH_SIZE` Generic
  src/rust/catcollar/runtime/network.rs
  src/rust/catnip/mod.rs
  src/rust/catnip/runtime/network.rs
  src/rust/catpowder/mod.rs
  src/rust/catpowder/runtime/network.rs
  src/rust/inetstack/mod.rs
  src/rust/inetstack/protocols/arp/peer.rs
  src/rust/inetstack/protocols/arp/tests.rs
  src/rust/inetstack/protocols/icmpv4/peer.rs
  src/rust/inetstack/protocols/icmpv4/tests.rs
  src/rust/inetstack/protocols/peer.rs
  src/rust/inetstack/protocols/queue.rs
  src/rust/inetstack/protocols/tcp/active_open.rs
  src/rust/inetstack/protocols/tcp/established/background/acknowledger.rs
  src/rust/inetstack/protocols/tcp/established/background/mod.rs
  src/rust/inetstack/protocols/tcp/established/background/retransmitter.rs
  src/rust/inetstack/protocols/tcp/established/background/sender.rs
  src/rust/inetstack/protocols/tcp/established/ctrlblk.rs
  src/rust/inetstack/protocols/tcp/established/mod.rs
  src/rust/inetstack/protocols/tcp/established/sender.rs
  src/rust/inetstack/protocols/tcp/operations.rs
  src/rust/inetstack/protocols/tcp/passive_open.rs
  src/rust/inetstack/protocols/tcp/peer.rs
  src/rust/inetstack/protocols/tcp/queue.rs
  src/rust/inetstack/protocols/tcp/tests/established.rs
  src/rust/inetstack/protocols/tcp/tests/setup.rs
  src/rust/inetstack/protocols/udp/peer.rs
  src/rust/inetstack/protocols/udp/tests.rs
  src/rust/inetstack/test_helpers/engine.rs
  src/rust/inetstack/test_helpers/mod.rs
  src/rust/inetstack/test_helpers/runtime.rs
  src/rust/runtime/network/mod.rs
  tests/rust/common/libos.rs
  tests/rust/common/runtime.rs
  tests/rust/tcp.rs
  tests/rust/udp.rs
Labels: enhancement

#737 [Runtime] Rename scheduler handle to task handle and other things to more useful things
  src/rust/catcollar/mod.rs
  src/rust/catloop/duplex_pipe.rs
  src/rust/catloop/futures/accept.rs
  src/rust/catloop/mod.rs
  src/rust/catmem/mod.rs
  src/rust/catnap/mod.rs
  src/rust/catnap/queue.rs
  src/rust/catnip/mod.rs
  src/rust/catpowder/mod.rs
  src/rust/demikernel/libos/memory.rs
  src/rust/demikernel/libos/mod.rs
  src/rust/demikernel/libos/network.rs
  src/rust/inetstack/mod.rs
  src/rust/inetstack/protocols/arp/peer.rs
  src/rust/inetstack/protocols/icmpv4/peer.rs
  src/rust/inetstack/protocols/tcp/active_open.rs
  src/rust/inetstack/protocols/tcp/established/mod.rs
  src/rust/inetstack/protocols/tcp/passive_open.rs
  src/rust/inetstack/protocols/udp/peer.rs
  src/rust/scheduler/handle.rs
  src/rust/scheduler/mod.rs
  src/rust/scheduler/scheduler.rs
Labels: enhancement

#733 [catnap] Transition to Connected State
  src/rust/catnap/mod.rs
Labels: bug

#738 [pipe-ping-pong] Refactor to add Drop
  examples/rust/pipe-ping-pong.rs
Labels: enhancement

#739 [bugfix] Poll in Every PDPIX Call
  src/rust/demikernel/libos/mod.rs
  tests/rust/sga.rs
Labels: bug

#735 [pdpix] Fix Network Types to be Compatible With Each Other
  src/rust/catcollar/futures/accept.rs
  src/rust/catcollar/futures/connect.rs
  src/rust/catcollar/iouring.rs
  src/rust/catcollar/mod.rs
  src/rust/catcollar/runtime/mod.rs
  src/rust/catloop/mod.rs
  src/rust/catnap/coroutines/accept.rs
  src/rust/catnap/coroutines/connect.rs
  src/rust/catnap/coroutines/pop.rs
  src/rust/catnap/coroutines/push.rs
  src/rust/catnap/mod.rs
  src/rust/catpowder/interop.rs
  src/rust/pal/linux/mod.rs
Labels: enhancement

#736 [doc] Socket States Diagram
  doc/diagrams/Demikernel - Socket States.png
  doc/diagrams/Demikernel - Socket States.vsdx
Labels: documentation
