Repository microsoft/demikernel, pull requests merged in 2023-03, with the labels that each got.

#494 [catcollar] Correctly Dree Data Structures on `close()`
  src/rust/catcollar/mod.rs
Labels: bug

#492 [catnap] Free queue descriptor on `close()`
  src/rust/catnap/mod.rs
Labels: bug

#496 [ci] Fixing Regression Pipeline for Catpowder
  .github/workflows/catpowder.yml
  tools/demikernel_ci.py
Labels: bug

#486 [runtime] Unify Queue Table Abstraction
  src/rust/catcollar/mod.rs
  src/rust/catcollar/queue.rs
  src/rust/catloop/mod.rs
  src/rust/catloop/queue.rs
  src/rust/catmem/mod.rs
  src/rust/catmem/queue.rs
  src/rust/catnap/mod.rs
  src/rust/catnap/queue.rs
  src/rust/inetstack/mod.rs
  src/rust/inetstack/protocols/mod.rs
  src/rust/inetstack/protocols/peer.rs
  src/rust/inetstack/protocols/queue.rs
  src/rust/inetstack/protocols/tcp/active_open.rs
  src/rust/inetstack/protocols/tcp/established/mod.rs
  src/rust/inetstack/protocols/tcp/mod.rs
  src/rust/inetstack/protocols/tcp/operations.rs
  src/rust/inetstack/protocols/tcp/passive_open.rs
  src/rust/inetstack/protocols/tcp/peer.rs
  src/rust/inetstack/protocols/tcp/queue.rs
  src/rust/inetstack/protocols/udp/mod.rs
  src/rust/inetstack/protocols/udp/peer.rs
  src/rust/inetstack/protocols/udp/queue.rs
  src/rust/inetstack/test_helpers/engine.rs
  src/rust/runtime/queue/mod.rs
  src/rust/runtime/queue/qtype.rs
Labels: enhancement

#500 [examples] TCP Bind Application
  examples/rust/linux.mk
  examples/tcp-bind/main.rs
Labels: enhancement

#506 [pal] Retrieve `errno` and Propagate It in `SharedMemory`
  src/rust/pal/linux/shm.rs
Labels: bug

#513 [runtime] Iterator over IO Queue Table
  src/rust/runtime/queue/mod.rs
Labels: enhancement

#514 [catloop] Do not Allow Multiple `bind()` to Same Address
  src/rust/catloop/mod.rs
Labels: bug

#515 [catnap] Do not Allow Multiple `bind()` to Same Address
  src/rust/catnap/mod.rs
  src/rust/catnap/queue.rs
Labels: bug

#516 [catcollar] Do not Allow Multiple `bind()` to Same Address
  src/rust/catcollar/mod.rs
  src/rust/catcollar/queue.rs
Labels: bug

#517 [inetstack] Fail to Close Bound and Unbound Sockets
  src/rust/inetstack/protocols/tcp/peer.rs
  tests/rust/tcp.rs
Labels: bug

#490 [catloop] Several Bug Fixes for Connection Establishment / Shutdown
  src/rust/catloop/duplex_pipe.rs
  src/rust/catloop/futures/accept.rs
  src/rust/catloop/futures/connect.rs
  src/rust/catmem/mod.rs
Labels: bug

#523 [tests] Drop `tcp_bad_bind()` in Favor of `tcp-bind`
  tests/rust/tcp.rs
  tools/demikernel_ci.py
Labels: enhancement

#524 [inetstack] Multiple Waiters for Address Resolution
  src/rust/inetstack/protocols/arp/peer.rs
Labels: bug

#528 [catnap] Implement async_close support
  src/rust/catnap/futures/close.rs
  src/rust/catnap/futures/mod.rs
  src/rust/catnap/mod.rs
  src/rust/demikernel/libos/network.rs
Labels: enhancement

#530 [inetstack] Implement async_close
  src/rust/inetstack/mod.rs
  src/rust/inetstack/protocols/tcp/established/ctrlblk.rs
  src/rust/inetstack/protocols/tcp/established/mod.rs
  src/rust/inetstack/protocols/tcp/operations.rs
  src/rust/inetstack/protocols/tcp/peer.rs
  src/rust/inetstack/protocols/udp/futures/operation.rs
Labels: enhancement

#531 [catnip] Implement async_close
  src/rust/catnip/interop.rs
  src/rust/demikernel/libos/network.rs
Labels: enhancement

#532 [catpowder] Implement async_close
  src/rust/catpowder/interop.rs
  src/rust/demikernel/libos/network.rs
Labels: enhancement

#533 [catcollar] Implement async_close
  src/rust/catcollar/futures/close.rs
  src/rust/catcollar/futures/mod.rs
  src/rust/catcollar/mod.rs
  src/rust/demikernel/libos/network.rs
Labels: enhancement

#534 [pdpix] Error Information in `demi_qresult_t`
  include/demi/types.h
  src/rust/catcollar/mod.rs
  src/rust/catloop/mod.rs
  src/rust/catmem/mod.rs
  src/rust/catnap/mod.rs
  src/rust/catnip/interop.rs
  src/rust/catpowder/interop.rs
  src/rust/runtime/types/ops.rs
Labels: bug

#548 [ci] Enable `tcp-accept` in Regressions
  tools/demikernel_ci.py
Labels: enhancement

#553 [ci] Support Test Alias
  tools/demikernel_ci.py
Labels: enhancement

#543 [examples] `tcp-close` Testing Program
  examples/rust/linux.mk
  examples/tcp-close/args.rs
  examples/tcp-close/client.rs
  examples/tcp-close/main.rs
  examples/tcp-close/server.rs
  examples/tcp-close/standalone.rs
Labels: enhancement

#545 [ci] Support `tcp-close` in `demikernel-ci`
  tools/demikernel_ci.py
Labels: enhancement

#546 [runtime] Improve Split Functionality in `DemiBuffer`
  src/rust/runtime/memory/demibuffer.rs
Labels: enhancement

#557 [catnap] Move from future to async coroutines
  src/rust/catnap/coroutines/accept.rs
  src/rust/catnap/coroutines/close.rs
  src/rust/catnap/coroutines/connect.rs
  src/rust/catnap/coroutines/mod.rs
  src/rust/catnap/coroutines/pop.rs
  src/rust/catnap/coroutines/push.rs
  src/rust/catnap/futures/close.rs
  src/rust/catnap/futures/connect.rs
  src/rust/catnap/futures/pop.rs
  src/rust/catnap/futures/push.rs
  src/rust/catnap/mod.rs
Labels: enhancement

#562 [test] Integration Tests for TCP
  Cargo.toml
  linux.mk
  tests/rust/tcp-test/accept/mod.rs
  tests/rust/tcp-test/args.rs
  tests/rust/tcp-test/bind/mod.rs
  tests/rust/tcp-test/close/mod.rs
  tests/rust/tcp-test/connect/mod.rs
  tests/rust/tcp-test/listen/mod.rs
  tests/rust/tcp-test/main.rs
  tests/rust/tcp-test/socket/mod.rs
Labels: enhancement

#558 [catnip] Append an empty string at eal_init args to be skipped
  scripts/config/default.yaml
Labels: bug

#564 [catmem] Fix incorrect size comparison
  src/rust/catmem/futures/pop.rs
Labels: bug

#569 [catnap] Several Fixes Around Socket State
  src/rust/catnap/mod.rs
  src/rust/catnap/queue.rs
  src/rust/catnap/socket.rs
Labels: bug

#570 [catmem] Invalid Queue Descriptor in Pop
  src/rust/catmem/mod.rs
Labels: bug

#572 [ci] Enable TCP Integration Tests for Catnap LibOS
  examples/rust/linux.mk
  examples/tcp-accept/args.rs
  examples/tcp-accept/client.rs
  examples/tcp-accept/main.rs
  examples/tcp-accept/server.rs
  examples/tcp-bind/main.rs
  examples/tcp-close/args.rs
  examples/tcp-close/main.rs
  examples/tcp-close/standalone.rs
  tools/demikernel_ci.py
Labels: enhancement

#573 [examples] Multi-Client Support for TCP Echo
  Cargo.toml
  examples/rust/tcp-echo/client.rs
  examples/rust/tcp-echo/server.rs
  examples/tcp-echo/client.rs
  examples/tcp-echo/main.rs
  examples/tcp-echo/server.rs
Labels: enhancement

#575 [test] Add tests for async_close
  tests/rust/tcp-test/close/async_close.rs
  tests/rust/tcp-test/close/mod.rs
Labels: enhancement

#576 [test] Add tests for wait after close
  tests/rust/tcp-test/close/mod.rs
  tests/rust/tcp-test/close/wait.rs
Labels: enhancement

#579 [ci] Enable `tcp-echo` for Catnap LibOS
  examples/tcp-echo/client.rs
  examples/tcp-echo/main.rs
  examples/tcp-echo/server.rs
  tools/demikernel_ci.py
Labels: enhancement

#583 [test] Integration Tests for TCP `bind()`
  src/rust/catnap/mod.rs
  tests/rust/tcp-test/bind/mod.rs
  tests/rust/tcp-test/main.rs
Labels: bug, enhancement

#586 [test] Integration Tests for TCP `accept()`
  tests/rust/tcp-test/accept/mod.rs
Labels: enhancement

#587 [test] Integration Tests for TCP `connect()`
  tests/rust/tcp-test/connect/mod.rs
Labels: enhancement

#581 [examples] Concurrent Mode for `tcp-echo`
  examples/tcp-echo/client.rs
  examples/tcp-echo/main.rs
  tools/demikernel_ci.py
Labels: enhancement
