Repository microsoft/demikernel, pull requests merged in 2023-06, with the labels that each got.

#749 [test] Don't Run Unit Tests Concurrently
  tools/demikernel_ci.py
Labels: bug

#754 [test] Enabling Testing Scenarios for TCP Wait
  examples/tcp-wait/client.rs
  tools/demikernel_ci.py
Labels: enhancement

#763 [doc] Adding Legal Documentation
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE.txt
  README.md
  SECURITY.md
  SUPPORT.md
Labels: documentation

#764 [runtime] Fix Scheduler Issues
  src/rust/scheduler/handle.rs
  src/rust/scheduler/scheduler.rs
Labels: bug

#770 [catloop] Leaking Tasks on Connection Establishment Protocol
  src/rust/catloop/futures/accept.rs
  src/rust/catloop/futures/connect.rs
Labels: bug

#761 [test] Don't Close Server-Side Passive Socket Twice in `tcp-close`
  examples/tcp-close/server.rs
Labels: bug

#766 [cleanup] Remove unnecessary code
  CONTRIBUTING.md
  man/demi_init.md
  src/rust/catloop/duplex_pipe.rs
  src/rust/catnapw/futures/accept.rs
  src/rust/catpowder/runtime/mod.rs
  src/rust/demikernel/bindings.rs
  src/rust/inetstack/protocols/tcp/established/ctrlblk.rs
  src/rust/runtime/memory/demibuffer.rs
  src/rust/scheduler/scheduler.rs
Labels: enhancement

#771 [catloop] Connection Establishment Does Not Cancel Inflight Pop Correctly
  src/rust/catloop/duplex_pipe.rs
  src/rust/catloop/futures/connect.rs
Labels: bug

#762 [catmem] Keep Track of Pending Operations
  src/rust/catmem/futures/pop.rs
  src/rust/catmem/futures/push.rs
  src/rust/catmem/mod.rs
  src/rust/catmem/queue.rs
Labels: enhancement

#779 [inetstack] Use TCP PSH bit
  src/rust/inetstack/protocols/tcp/established/background/sender.rs
  src/rust/inetstack/protocols/tcp/established/ctrlblk.rs
  src/rust/inetstack/protocols/tcp/established/sender.rs
Labels: enhancement

#782 [runtime] Fixing issues in scheduler
  src/rust/scheduler/scheduler.rs
Labels: bug

#780 [test] Enable All Async Close Tests for TCP
  tests/rust/tcp-test/accept/mod.rs
  tests/rust/tcp-test/async_close/mod.rs
  tests/rust/tcp-test/bind/mod.rs
  tests/rust/tcp-test/close/mod.rs
  tests/rust/tcp-test/connect/mod.rs
  tests/rust/tcp-test/listen/mod.rs
  tests/rust/tcp-test/main.rs
  tests/rust/tcp-test/socket/mod.rs
  tests/rust/tcp-test/wait/mod.rs
Labels: bug, enhancement

#783 [catmem] Missing `async_close`
  src/rust/catmem/futures/close.rs
  src/rust/catmem/futures/mod.rs
  src/rust/catmem/mod.rs
  src/rust/demikernel/libos/memory.rs
  src/rust/demikernel/libos/mod.rs
  tests/rust/pipe-test/async_close/mod.rs
  tools/demikernel_ci.py
Labels: bug

#784 [test] Missing cases on IPv4 test-unit
  src/rust/inetstack/protocols/ipv4/datagram.rs
  src/rust/inetstack/protocols/ipv4/tests.rs
Labels: bug

#789 [bindings] Structures Are Not Packed
  include/demi/types.h
Labels: bug

#790 [bindings] Check for Invalid Storage Location
  src/rust/demikernel/bindings.rs
Labels: bug

#791 [catloop] Missing to Shift Catmem Queue Tokens When Packing Result
  src/rust/catloop/mod.rs
Labels: bug

#785 [catloop] Move to async functions and add yield and cancel on close
  src/rust/catloop/duplex_pipe.rs
  src/rust/catloop/futures/accept.rs
  src/rust/catloop/futures/connect.rs
  src/rust/catloop/mod.rs
  src/rust/catloop/queue.rs
  src/rust/scheduler/yielder.rs
Labels: enhancement

#772 [inetstack] Generic Checksum
  src/rust/inetstack/protocols/icmpv4/datagram/header.rs
  src/rust/inetstack/protocols/mod.rs
Labels: enhancement

#793 [catmem] Rename schedule function
  src/rust/catloop/futures/accept.rs
  src/rust/catloop/futures/connect.rs
  src/rust/catloop/mod.rs
  src/rust/catmem/mod.rs
  src/rust/demikernel/libos/memory.rs
Labels: enhancement

#794 [catmem] Name Prefix Shared Memory Regions
  linux.mk
  src/rust/pal/linux/shm.rs
Labels: bug, enhancement

#795 [test] Add Barrier to Ring Buffer Test
  src/rust/collections/shared_ring.rs
Labels: bug, enhancement

#798 [catloop] Rollback Port Allocation
  src/rust/catloop/futures/accept.rs
  src/rust/catloop/mod.rs
Labels: bug

#799 [tests] Turn on and fix Pipe Integration Tests
  linux.mk
  src/rust/catmem/futures/push.rs
  tests/rust/pipe-test/pop_wait/client.rs
  tests/rust/pipe-test/pop_wait/server.rs
  tests/rust/pipe-test/push_wait/client.rs
  tests/rust/pipe-test/push_wait/server.rs
  tools/demikernel_ci.py
Labels: bug

#806 [catmem] Broken Trace Statement
  src/rust/catcollar/futures/connect.rs
Labels: bug

#801 [catmem] States For Pipes
  src/rust/catmem/mod.rs
  src/rust/catmem/pipe.rs
Labels: enhancement

#805 [catmem] Add Drop Function
  src/rust/catmem/mod.rs
Labels: bug
