Repository microsoft/demikernel, pull requests merged in 2023-01, with the labels that each got.

#392 [doc] Fixing Minor Typos on Testing Instructions
  doc/testing.md
Labels: documentation

#391 [test] `tcp-ping-pong` Does Not Wait for Full Receive Buffer
  examples/rust/tcp-ping-pong.rs
  include/demi/libos.h
  src/rust/demikernel/libos/network.rs
Labels: bug

#393 [build] Fixing Build Warnings
  examples/rust/tcp-dump.rs
  src/rust/catcollar/futures/pop.rs
  src/rust/collections/ring.rs
  src/rust/collections/shared_ring.rs
  src/rust/lib.rs
  src/rust/perftools/profiler/mod.rs
  tests/rust/udp.rs
Labels: enhancement

#396 [ci] Enhancement: Support Config Path Override
  tools/demikernel-ci.py
Labels: enhancement

#398 [tools] Support NFS Directories in `demikernel-ci`
  tools/demikernel-ci.py
Labels: enhancement

#408 [build] Set `RUST_LOG=trace` when Running in Debug Mode
  linux.mk
Labels: enhancement

#406 [pal] Bad Level When Setting `SO_REUSEPORT`
  src/rust/pal/linux/mod.rs
Labels: bug

#411 [tools] Bad Check on Number of Executed Jobs in `demikernel-ci`
  tools/demikernel-ci.py
Labels: bug

#399 [doc] Moving Build Instructions to Standalone Document
  README.md
  doc/building.md
  doc/testing.md
Labels: enhancement, documentation

#413 [pal] Helper Function to Convert `std::net::SocketAddrV4` to `libc::sockaddr_in`
  src/rust/catcollar/mod.rs
  src/rust/catnap/mod.rs
  src/rust/catpowder/interop.rs
  src/rust/pal/linux/mod.rs
Labels: enhancement

#415 [tools] Adding support for test directories and log files with hostnames
  tools/demikernel-ci.py
Labels: enhancement

#418 [tools] Minor Bug Fixes in `demikernel-ci`
  tools/demikernel-ci.py
Labels: bug

#428 [inetstack] Handle Cancellation of Ping Requests
  src/rust/inetstack/protocols/icmpv4/peer.rs
Labels: bug

#429 [tools] Initial Azure Tables support
  doc/testing.md
  scripts/setup/debian.sh
  tools/azure_tables.py
  tools/demikernel_ci.py
Labels: enhancement

#427 [build] Drop Dependency on Some Crates
  Cargo.toml
  src/rust/inetstack/protocols/arp/packet/header.rs
  src/rust/inetstack/protocols/ethernet2/protocol.rs
  src/rust/inetstack/protocols/ip/protocol.rs
  src/rust/lib.rs
  src/rust/runtime/network/types/portnum.rs
  src/rust/runtime/queue/qdesc.rs
  src/rust/runtime/queue/qtoken.rs
Labels: enhancement

#419 [build] Dropping Dependency on `nix`
  Cargo.toml
  src/rust/catcollar/futures/accept.rs
  src/rust/catcollar/futures/connect.rs
  src/rust/catcollar/iouring.rs
  src/rust/catcollar/mod.rs
  src/rust/catcollar/runtime/mod.rs
  src/rust/catnap/futures/accept.rs
  src/rust/catnap/futures/connect.rs
  src/rust/catnap/futures/pop.rs
  src/rust/catnap/futures/push.rs
  src/rust/catnap/futures/pushto.rs
  src/rust/catnap/mod.rs
  src/rust/catpowder/runtime/rawsocket/rawsocket.rs
  src/rust/pal/linux/mod.rs
Labels: enhancement

#436 [catcollar] Bad Logic for Async Ongoing Operations
  src/rust/catcollar/futures/pop.rs
  src/rust/catcollar/futures/push.rs
  src/rust/catcollar/futures/pushto.rs
  src/rust/catcollar/iouring.rs
  src/rust/catcollar/mod.rs
  src/rust/catcollar/runtime/mod.rs
Labels: bug

#439 [memory] Marking old APIs as deprecated
  src/rust/runtime/memory/buffer/databuffer.rs
  src/rust/runtime/memory/buffer/dpdkbuffer.rs
Labels: enhancement

#437 [winport] Update the Windows crate 0.44.0
  Cargo.toml
  examples/rust/udp-echo.rs
  src/rust/catnapw/mod.rs
  src/rust/demikernel/bindings.rs
  src/rust/inetstack/mod.rs
  src/rust/pal/constants.rs
Labels: enhancement

#440 [runtime] Unify memory runtime
  src/rust/catcollar/runtime/memory.rs
  src/rust/catcollar/runtime/mod.rs
  src/rust/catmem/mod.rs
  src/rust/catnap/runtime.rs
  src/rust/catnapw/runtime.rs
  src/rust/catpowder/runtime/memory.rs
  src/rust/catpowder/runtime/mod.rs
  src/rust/runtime/memory/mod.rs
Labels: enhancement

#438 [pdpix] Remote Address Is Not Set In `demi_accept_result_t`
  src/rust/catcollar/futures/accept.rs
  src/rust/catcollar/futures/mod.rs
  src/rust/catcollar/mod.rs
  src/rust/catloop/mod.rs
  src/rust/catnap/futures/accept.rs
  src/rust/catnap/futures/mod.rs
  src/rust/catnap/mod.rs
  src/rust/catnip/interop.rs
  src/rust/catpowder/interop.rs
  src/rust/inetstack/operations.rs
  src/rust/inetstack/protocols/tcp/operations.rs
  src/rust/inetstack/protocols/tcp/peer.rs
  src/rust/inetstack/protocols/tcp/tests/established.rs
  src/rust/inetstack/protocols/tcp/tests/setup.rs
  tests/rust/tcp.rs
Labels: bug

#446 [catnapw] Set Remote Address in Accept
  src/rust/catnapw/futures/accept.rs
  src/rust/catnapw/futures/mod.rs
  src/rust/catnapw/mod.rs
Labels: bug

#441 [runtime] 32-Bit Queue Descriptors
  src/rust/inetstack/protocols/udp/tests.rs
  src/rust/runtime/queue/mod.rs
  src/rust/runtime/queue/qdesc.rs
Labels: enhancement
