Repository microsoft/demikernel, pull requests merged in 2023-11, with the labels that each got.

#986 [runtime] Move watched value to current architecture
  src/rust/collections/intrusive/double_linked_list.rs
  src/rust/collections/intrusive/mod.rs
  src/rust/inetstack/protocols/tcp/established/background/acknowledger.rs
  src/rust/inetstack/protocols/tcp/established/background/retransmitter.rs
  src/rust/inetstack/protocols/tcp/established/background/sender.rs
  src/rust/inetstack/protocols/tcp/established/congestion_control/cubic.rs
  src/rust/inetstack/protocols/tcp/established/congestion_control/mod.rs
  src/rust/inetstack/protocols/tcp/established/congestion_control/none.rs
  src/rust/inetstack/protocols/tcp/established/ctrlblk.rs
  src/rust/inetstack/protocols/tcp/established/mod.rs
  src/rust/inetstack/protocols/tcp/established/sender.rs
  src/rust/inetstack/protocols/tcp/peer.rs
  src/rust/runtime/mod.rs
  src/rust/runtime/watched.rs
Labels: enhancement

#989 [collections] Enhancement: Remove unnecessary linked list
  src/rust/collections/async_queue.rs
Labels: enhancement

#991 [catcollar] Move to SharedDemiRuntime
  src/rust/catcollar/mod.rs
  src/rust/catcollar/runtime/mod.rs
  src/rust/demikernel/libos/mod.rs
  src/rust/inetstack/test_helpers/runtime.rs
  src/rust/runtime/mod.rs
  src/rust/runtime/queue/mod.rs
  tests/rust/common/libos.rs
Labels: enhancement

#994 [runtime] Enhancement: Move clock to runtime
  src/rust/catnip/mod.rs
  src/rust/catpowder/mod.rs
  src/rust/inetstack/futures/mod.rs
  src/rust/inetstack/futures/utilities.rs
  src/rust/inetstack/mod.rs
  src/rust/inetstack/protocols/arp/cache/mod.rs
  src/rust/inetstack/protocols/arp/cache/tests.rs
  src/rust/inetstack/protocols/arp/peer.rs
  src/rust/inetstack/protocols/icmpv4/peer.rs
  src/rust/inetstack/protocols/peer.rs
  src/rust/inetstack/protocols/tcp/active_open.rs
  src/rust/inetstack/protocols/tcp/established/background/acknowledger.rs
  src/rust/inetstack/protocols/tcp/established/background/retransmitter.rs
  src/rust/inetstack/protocols/tcp/established/background/sender.rs
  src/rust/inetstack/protocols/tcp/established/ctrlblk.rs
  src/rust/inetstack/protocols/tcp/established/sender.rs
  src/rust/inetstack/protocols/tcp/passive_open.rs
  src/rust/inetstack/protocols/tcp/peer.rs
  src/rust/inetstack/test_helpers/engine.rs
  src/rust/inetstack/test_helpers/runtime.rs
  src/rust/runtime/mod.rs
  src/rust/runtime/timer.rs
  tests/rust/common/libos.rs
Labels: enhancement

#996 [runtime] Remove file descriptor from socket id data structure
  src/rust/runtime/network/socket/mod.rs
Labels: bug

#999 [runtime] Enhancement: Remove a warning
  src/rust/runtime/network/ephemeral.rs
Labels: enhancement

#997 [runtime] Enhancement: add more tracing
  src/rust/runtime/mod.rs
  src/rust/runtime/network/socket/mod.rs
Labels: enhancement

#998 [inetstack] Remove spurious wake ups
  src/rust/inetstack/protocols/arp/peer.rs
  src/rust/inetstack/protocols/icmpv4/peer.rs
  src/rust/inetstack/protocols/tcp/active_open.rs
  src/rust/inetstack/protocols/tcp/established/background/acknowledger.rs
  src/rust/inetstack/protocols/tcp/established/background/mod.rs
  src/rust/inetstack/protocols/tcp/established/background/retransmitter.rs
  src/rust/inetstack/protocols/tcp/established/background/sender.rs
  src/rust/inetstack/protocols/tcp/established/mod.rs
  src/rust/inetstack/protocols/tcp/passive_open.rs
  src/rust/inetstack/protocols/tcp/peer.rs
  src/rust/runtime/timer.rs
  src/rust/scheduler/handle.rs
  src/rust/scheduler/scheduler.rs
Labels: bug

#1004 [demikernel] Switch to `runtime::pack_result()` for `catcollar` and `catpowder`
  src/rust/catcollar/mod.rs
  src/rust/catloop/mod.rs
  src/rust/catnap/mod.rs
  src/rust/catpowder/interop.rs
  src/rust/catpowder/mod.rs
Labels: enhancement

#1001 [inetstack] Move TCP stack to objects
  src/rust/inetstack/mod.rs
  src/rust/inetstack/protocols/tcp/active_open.rs
  src/rust/inetstack/protocols/tcp/established/mod.rs
  src/rust/inetstack/protocols/tcp/established/sender.rs
  src/rust/inetstack/protocols/tcp/passive_open.rs
  src/rust/inetstack/protocols/tcp/peer.rs
  src/rust/inetstack/protocols/tcp/queue.rs
  src/rust/inetstack/protocols/tcp/tests/established.rs
  src/rust/inetstack/protocols/tcp/tests/setup.rs
  src/rust/inetstack/test_helpers/engine.rs
  tests/rust/tcp.rs
Labels: enhancement

#1005 [runtime] Move the scheduler src into runtime src tree
  src/rust/catcollar/mod.rs
  src/rust/catcollar/runtime/mod.rs
  src/rust/catloop/mod.rs
  src/rust/catloop/queue.rs
  src/rust/catloop/socket.rs
  src/rust/catmem/mod.rs
  src/rust/catmem/queue.rs
  src/rust/catnap/mod.rs
  src/rust/catnap/queue.rs
  src/rust/catnap/socket.rs
  src/rust/catnip/mod.rs
  src/rust/catpowder/mod.rs
  src/rust/collections/async_queue.rs
  src/rust/collections/async_value.rs
  src/rust/demikernel/libos/memory.rs
  src/rust/demikernel/libos/mod.rs
  src/rust/demikernel/libos/network.rs
  src/rust/inetstack/mod.rs
  src/rust/inetstack/protocols/arp/peer.rs
  src/rust/inetstack/protocols/icmpv4/peer.rs
  src/rust/inetstack/protocols/tcp/active_open.rs
  src/rust/inetstack/protocols/tcp/established/background/acknowledger.rs
  src/rust/inetstack/protocols/tcp/established/background/mod.rs
  src/rust/inetstack/protocols/tcp/established/background/retransmitter.rs
  src/rust/inetstack/protocols/tcp/established/background/sender.rs
  src/rust/inetstack/protocols/tcp/established/ctrlblk.rs
  src/rust/inetstack/protocols/tcp/established/mod.rs
  src/rust/inetstack/protocols/tcp/passive_open.rs
  src/rust/inetstack/protocols/tcp/peer.rs
  src/rust/inetstack/protocols/tcp/queue.rs
  src/rust/inetstack/protocols/tcp/tests/established.rs
  src/rust/inetstack/protocols/tcp/tests/setup.rs
  src/rust/inetstack/protocols/udp/peer.rs
  src/rust/inetstack/protocols/udp/queue.rs
  src/rust/lib.rs
  src/rust/runtime/mod.rs
  src/rust/runtime/queue/mod.rs
  src/rust/runtime/scheduler/handle.rs
  src/rust/runtime/scheduler/mod.rs
  src/rust/runtime/scheduler/mutex.rs
  src/rust/runtime/scheduler/page/mod.rs
  src/rust/runtime/scheduler/page/page.rs
  src/rust/runtime/scheduler/page/page_ref.rs
  src/rust/runtime/scheduler/page/waker_ref.rs
  src/rust/runtime/scheduler/pin_slab.rs
  src/rust/runtime/scheduler/scheduler.rs
  src/rust/runtime/scheduler/task.rs
  src/rust/runtime/scheduler/waker64.rs
  src/rust/runtime/scheduler/yielder.rs
  src/rust/runtime/timer.rs
  src/rust/runtime/watched.rs
Labels: enhancement

#1006 [ci] Reenable Catnap CI on Windows
  .github/workflows/catnapw.yml
Labels: bug

#1003 [inetstack] Move UDP stack to objects
  src/rust/collections/async_queue.rs
  src/rust/inetstack/mod.rs
  src/rust/inetstack/protocols/arp/peer.rs
  src/rust/inetstack/protocols/icmpv4/peer.rs
  src/rust/inetstack/protocols/tcp/active_open.rs
  src/rust/inetstack/protocols/tcp/established/background/sender.rs
  src/rust/inetstack/protocols/tcp/established/ctrlblk.rs
  src/rust/inetstack/protocols/tcp/passive_open.rs
  src/rust/inetstack/protocols/udp/peer.rs
  src/rust/inetstack/protocols/udp/queue.rs
  src/rust/inetstack/protocols/udp/tests.rs
  src/rust/inetstack/test_helpers/engine.rs
Labels: enhancement

#1009 [ci] Enabling Debug Runs for Catnip and Catpowder
  .github/workflows/catnip.yml
  .github/workflows/catpowder.yml
Labels: enhancement

#1008 [inetstack] Move TCP stack to use shared state machine
  src/rust/catnip/mod.rs
  src/rust/catpowder/mod.rs
  src/rust/inetstack/mod.rs
  src/rust/inetstack/protocols/tcp/passive_open.rs
  src/rust/inetstack/protocols/tcp/peer.rs
  src/rust/inetstack/protocols/tcp/queue.rs
  src/rust/inetstack/protocols/tcp/tests/established.rs
  src/rust/inetstack/protocols/tcp/tests/setup.rs
  src/rust/inetstack/test_helpers/engine.rs
  src/rust/runtime/mod.rs
  tests/rust/tcp.rs
Labels: enhancement

#1011 [inetstack] Use correct include for platform
  src/rust/inetstack/protocols/tcp/queue.rs
Labels: bug

#1014 [ci] Run Catnap CI on Windows on Head Branches of PRs
  .github/workflows/catnapw.yml
Labels: bug

#1013 [testing] Turn on TCP echo tests for inetstack
  tools/ci/config/ci_map.yaml
Labels: enhancement

#1015 [inetstack] Finish implementing async tcp close
  src/rust/inetstack/protocols/tcp/established/ctrlblk.rs
  src/rust/inetstack/protocols/tcp/established/mod.rs
  src/rust/inetstack/protocols/tcp/peer.rs
  src/rust/inetstack/protocols/tcp/queue.rs
Labels: enhancement

#1016 [ci] Gather and Upload Performance Statistics
  .github/workflows/catcollar.yml
  .github/workflows/catloop.yml
  .github/workflows/catmem.yml
  .github/workflows/catnap.yml
  .github/workflows/catnip.yml
  .github/workflows/catpowder.yml
  src/rust/perftools/profiler/mod.rs
  tools/demikernel_ci.py
Labels: enhancement

#1021 [contrib] Updating Dependencies
  Cargo.toml
  rust-toolchain
Labels: enhancement

#1019 [catnap] Enhancement: Move to socket2
  src/rust/catloop/socket.rs
  src/rust/catnap/mod.rs
  src/rust/catnap/queue.rs
  src/rust/catnap/socket.rs
  src/rust/catnap/transport.rs
  src/rust/demikernel/libos/network.rs
  src/rust/inetstack/protocols/tcp/queue.rs
  src/rust/pal/linux/mod.rs
  src/rust/runtime/network/socket/state.rs
  tests/rust/tcp-test/bind/mod.rs
Labels: enhancement

#1034 [build] Fix Build Warnings
  src/rust/inetstack/protocols/icmpv4/datagram/mod.rs
  src/rust/inetstack/protocols/udp/datagram/mod.rs
Labels: enhancement

#1032 [test] Integrate Catnap Windows on CI Tool and Infrastructure
  .github/workflows/catnapw.yml
  tools/demikernel_ci.py
  windows.mk
Labels: enhancement

#1027 [test] TCP Simulation Testing
  Cargo.toml
  linux.mk
  nettest/Cargo.toml
  nettest/LICENSE.txt
  nettest/README.md
  nettest/build.rs
  nettest/input/blocking-accept.pkt
  nettest/src/glue.rs
  nettest/src/grammar.y
  nettest/src/lib.rs
  nettest/src/main.rs
  nettest/src/tokens.l
  src/rust/inetstack/protocols/tcp/segment.rs
  src/rust/inetstack/protocols/tcp/tests/mod.rs
  src/rust/inetstack/protocols/tcp/tests/simulator.rs
  windows.mk
Labels: feature

#1037 [demikernel] Improve pending_ops lifecycle management
  src/rust/catcollar/mod.rs
  src/rust/catloop/mod.rs
  src/rust/catloop/queue.rs
  src/rust/catloop/socket.rs
  src/rust/catnap/mod.rs
  src/rust/catnap/queue.rs
  src/rust/catnip/mod.rs
  src/rust/catpowder/mod.rs
  src/rust/runtime/mod.rs
Labels: enhancement
