Repository microsoft/demikernel, pull requests merged in 2023-04, with the labels that each got.

#585 [test] Integration Tests for TCP `listen()`
  src/rust/catnap/mod.rs
  tests/rust/tcp-test/listen/mod.rs
Labels: bug, enhancement

#614 [doc] Reword TODOs in Source Tree
  src/rust/catloop/mod.rs
  src/rust/catnip/runtime/memory/manager.rs
  src/rust/catnip/runtime/network.rs
  src/rust/catpowder/runtime/network.rs
  src/rust/inetstack/protocols/tcp/established/background/retransmitter.rs
  src/rust/inetstack/protocols/tcp/established/background/sender.rs
  src/rust/inetstack/protocols/tcp/established/congestion_control/cubic.rs
  src/rust/inetstack/protocols/tcp/established/ctrlblk.rs
  src/rust/inetstack/protocols/tcp/established/rto.rs
  src/rust/inetstack/protocols/tcp/established/sender.rs
  src/rust/inetstack/protocols/tcp/tests/mod.rs
  src/rust/runtime/memory/demibuffer.rs
  src/rust/runtime/memory/mod.rs
  src/rust/runtime/types/memory.rs
Labels: documentation

#595 [catmem] Connection Reset in Push and Pop
  examples/pipe-open/server.rs
  src/rust/catmem/mod.rs
Labels: bug

#596 [build] Drop Use of `new_uninit`
  src/rust/lib.rs
  tests/rust/tcp.rs
  tests/rust/udp.rs
Labels: enhancement

#592 [runtime] Adding correct cancellation of queue tokens on queue close
  src/rust/catnap/coroutines/accept.rs
  src/rust/catnap/coroutines/close.rs
  src/rust/catnap/coroutines/connect.rs
  src/rust/catnap/coroutines/pop.rs
  src/rust/catnap/coroutines/push.rs
  src/rust/catnap/mod.rs
  src/rust/catnap/queue.rs
  src/rust/scheduler/coop_yield.rs
  src/rust/scheduler/handle.rs
  src/rust/scheduler/mod.rs
  src/rust/scheduler/task.rs
  src/rust/scheduler/yielder.rs
  tests/rust/tcp-test/accept/mod.rs
  tests/rust/tcp-test/close/async_close.rs
  tests/rust/tcp-test/close/wait.rs
  tests/rust/tcp-test/connect/mod.rs
  tests/rust/tcp-test/listen/mod.rs
Labels: enhancement

#594 [inetstack] ICMP echo reply
  src/rust/inetstack/protocols/icmpv4/datagram/header.rs
  src/rust/inetstack/protocols/icmpv4/datagram/message.rs
  src/rust/inetstack/protocols/icmpv4/datagram/mod.rs
  src/rust/inetstack/protocols/icmpv4/datagram/protocol.rs
  src/rust/inetstack/protocols/icmpv4/peer.rs
Labels: bug

#627 [test] Removing Scheduler Assumptions from Tests
  tests/rust/tcp-test/accept/mod.rs
  tests/rust/tcp-test/close/async_close.rs
  tests/rust/tcp-test/close/mod.rs
  tests/rust/tcp-test/close/wait.rs
  tests/rust/tcp-test/connect/mod.rs
  tests/rust/tcp-test/listen/mod.rs
Labels: bug

#628 [test] Add sanity check to payload order
  examples/rust/tcp-ping-pong.rs
Labels: enhancement

#623 [catloop] Collisions on Queue Token Space
  src/rust/catloop/mod.rs
Labels: bug

#636 [catmem] Redimensioning Ring Buffer
  src/rust/catmem/mod.rs
Labels: enhancement

#637 [test] Remove panic, expect and unwrap from integration tests
  tests/rust/common/libos.rs
  tests/rust/sga.rs
  tests/rust/tcp.rs
  tests/rust/udp.rs
Labels: bug

#639 [test] Remove panics from pipe-open system test
  examples/pipe-open/client.rs
  examples/pipe-open/server.rs
Labels: bug

#630 [tcp-close] New whocloses semantics
  examples/tcp-close/args.rs
  examples/tcp-close/client.rs
  examples/tcp-close/main.rs
  examples/tcp-close/server.rs
  tools/demikernel_ci.py
Labels: enhancement

#643 [test] Remove panics from tcp-echo system test
  examples/tcp-echo/client.rs
  examples/tcp-echo/main.rs
  examples/tcp-echo/server.rs
Labels: bug

#641 [test] Remove panics from tcp-close system test
  examples/tcp-close/client.rs
  examples/tcp-close/server.rs
Labels: bug

#644 [test] Integration Tests for TCP `create_pipe()`
  Cargo.toml
  linux.mk
  tests/rust/pipe-test/args.rs
  tests/rust/pipe-test/create_pipe/mod.rs
  tests/rust/pipe-test/main.rs
  tools/demikernel_ci.py
Labels: enhancement

#648 [test] Remove panic from pipe system tests
  examples/rust/pipe-ping-pong.rs
  examples/rust/pipe-push-pop.rs
Labels: bug

#650 [test] Remove panic from TCP system tests
  examples/rust/tcp-dump.rs
  examples/rust/tcp-ping-pong.rs
  examples/rust/tcp-pktgen.rs
  examples/rust/tcp-push-pop.rs
Labels: bug

#652 [test] Remove panic from UDP system tests
  examples/rust/udp-dump.rs
  examples/rust/udp-echo.rs
  examples/rust/udp-ping-pong.rs
  examples/rust/udp-pktgen.rs
  examples/rust/udp-push-pop.rs
  examples/rust/udp-relay.rs
Labels: bug

#654 [test] wait(): Add TCP tests around wait()/close()
  tests/rust/tcp-test/close/wait.rs
Labels: enhancement

#656 [test] Add `ensure_eq!` macro
  src/rust/lib.rs
Labels: enhancement

#655 [test] Integration Tests for TCP `open_pipe()`
  tests/rust/pipe-test/create_pipe/mod.rs
  tests/rust/pipe-test/main.rs
  tests/rust/pipe-test/open_pipe/mod.rs
Labels: enhancement

#658 [tcp-close] Add `async_close()` support
  examples/tcp-close/args.rs
  examples/tcp-close/client.rs
  examples/tcp-close/main.rs
  examples/tcp-close/server.rs
Labels: enhancement

#657 [test] Remove panic from collections unit tests
  src/rust/collections/intrusive/intrusive_queue.rs
  src/rust/collections/raw_array.rs
  src/rust/collections/ring.rs
  src/rust/collections/shared_ring.rs
Labels: bug

#660 [test] Integration Tests for Pipe `close`
  tests/rust/pipe-test/close/mod.rs
  tests/rust/pipe-test/main.rs
Labels: enhancement

#663 [test] Remove panic from pal and perftools unit tests
  src/rust/pal/linux/shm.rs
  src/rust/perftools/profiler/tests.rs
Labels: bug

#664 [test] Remove panic from scheduler unit test
  src/rust/scheduler/page/page.rs
  src/rust/scheduler/page/page_ref.rs
  src/rust/scheduler/page/waker_ref.rs
  src/rust/scheduler/pin_slab.rs
  src/rust/scheduler/scheduler.rs
Labels: bug

#662 [test] Integration Tests for Pipe `async_close()`
  tests/rust/pipe-test/async_close/mod.rs
  tests/rust/pipe-test/main.rs
Labels: enhancement

#667 [catmem] Don't Check for EoF on Push
  src/rust/catmem/mod.rs
Labels: bug

#676 [test] Rich CLI for C System Tests
  examples/c/pipe-ping-pong.c
  examples/c/pipe-push-pop.c
  examples/c/tcp-ping-pong.c
  examples/c/tcp-push-pop.c
  examples/c/udp-ping-pong.c
  examples/c/udp-push-pop.c
Labels: enhancement

#678 [test] Fix compiler errors and warnings
  examples/rust/udp-echo.rs
  src/rust/catnap/socket.rs
  src/rust/inetstack/protocols/tcp/tests/established.rs
  src/rust/inetstack/protocols/tcp/tests/mod.rs
  src/rust/inetstack/protocols/tcp/tests/setup.rs
  src/rust/perftools/profiler/tests.rs
  src/rust/runtime/memory/demibuffer.rs
Labels: bug

#677 [test] Wait Push After Closing Pipe
  tests/rust/pipe-test/args.rs
  tests/rust/pipe-test/main.rs
  tests/rust/pipe-test/push_wait/client.rs
  tests/rust/pipe-test/push_wait/mod.rs
  tests/rust/pipe-test/push_wait/server.rs
Labels: enhancement

#682 [test] Enable `PROFILER` Flag in `demikernel_ci`
  tools/demikernel_ci.py
Labels: enhancement

#681 [test] Remove assert from integration tests
  tests/rust/tcp-test/accept/mod.rs
  tests/rust/tcp-test/bind/mod.rs
  tests/rust/tcp-test/close/async_close.rs
  tests/rust/tcp-test/close/mod.rs
  tests/rust/tcp-test/connect/mod.rs
  tests/rust/tcp-test/listen/mod.rs
  tests/rust/tcp-test/socket/mod.rs
Labels: bug

#686 [catmem] Don't Push EoF Indefinitely
  src/rust/catmem/mod.rs
Labels: bug

#683 [test] Wait Pop After Closing Pipe
  tests/rust/pipe-test/args.rs
  tests/rust/pipe-test/main.rs
  tests/rust/pipe-test/pop_wait/client.rs
  tests/rust/pipe-test/pop_wait/mod.rs
  tests/rust/pipe-test/pop_wait/server.rs
Labels: enhancement

#688 [test] Switch to collect macro for tcp integration tests
  tests/rust/tcp-test/accept/mod.rs
  tests/rust/tcp-test/bind/mod.rs
  tests/rust/tcp-test/close/async_close.rs
  tests/rust/tcp-test/close/mod.rs
  tests/rust/tcp-test/close/wait.rs
  tests/rust/tcp-test/connect/mod.rs
  tests/rust/tcp-test/listen/mod.rs
  tests/rust/tcp-test/main.rs
  tests/rust/tcp-test/socket/mod.rs
Labels: enhancement

#691 [catmem] Release Queue Descriptor Even If `close()` Fails
  src/rust/catmem/mod.rs
Labels: enhancement

#692 [test] Wait on Invalid Queue Token Pipe
  tests/rust/pipe-test/main.rs
  tests/rust/pipe-test/wait/mod.rs
Labels: enhancement

#693 [test] Wait Push After Asynchronous Close
  tests/rust/pipe-test/args.rs
  tests/rust/pipe-test/main.rs
  tests/rust/pipe-test/push_wait/client.rs
Labels: enhancement

#694 [test] Wait Pop After Asynchronous Close Pipe
  tests/rust/pipe-test/args.rs
  tests/rust/pipe-test/main.rs
  tests/rust/pipe-test/pop_wait/server.rs
Labels: enhancement

#695 [test] Test Macros for Demikernel
  src/rust/lib.rs
  tests/rust/pipe-test/async_close/mod.rs
  tests/rust/pipe-test/close/mod.rs
  tests/rust/pipe-test/create_pipe/mod.rs
  tests/rust/pipe-test/main.rs
  tests/rust/pipe-test/open_pipe/mod.rs
  tests/rust/pipe-test/wait/mod.rs
Labels: enhancement

#699 [pdpix] Have a System-Wide Maximum Size for a Receive Buffer
  src/rust/catcollar/mod.rs
  src/rust/catmem/futures/pop.rs
  src/rust/catnap/coroutines/pop.rs
  src/rust/catpowder/runtime/network.rs
  src/rust/runtime/limits.rs
  src/rust/runtime/mod.rs
Labels: enhancement

#700 [pdpix] Consistent Behavior When `listen()` with Invalid Backlog Length
  src/rust/catcollar/mod.rs
  src/rust/catloop/mod.rs
  src/rust/catnap/mod.rs
  src/rust/demikernel/libos/network.rs
  src/rust/inetstack/mod.rs
Labels: bug

#689 [test] Add test for Catmem LibOS cleanup
  tests/rust/pipe-test/create_pipe/mod.rs
Labels: enhancement

#703 [pdpix] Have an Upper Limit for Fixed-Size `pop()`s
  src/rust/catcollar/mod.rs
  src/rust/catloop/mod.rs
  src/rust/catmem/mod.rs
  src/rust/catnap/mod.rs
  src/rust/demikernel/libos/mod.rs
  src/rust/inetstack/mod.rs
  src/rust/runtime/limits.rs
Labels: enhancement

#690 [test] Add tcp_wait utility
  examples/rust/linux.mk
  examples/tcp-wait/args.rs
  examples/tcp-wait/client.rs
  examples/tcp-wait/main.rs
  examples/tcp-wait/server.rs
  tools/demikernel_ci.py
Labels: enhancement
