Repository microsoft/demikernel, pull requests merged in 2024-05, with the labels that each got.

#1259 [contrib] Updating Third-Party Dependencies
  Cargo.toml
  dpdk-rs/Cargo.toml
  nettest/Cargo.toml
  rust-toolchain
Labels: enhancement

#1261 [shim] Correctly Interpose `fcntl()`
  shim/src/interpose.c
Labels: bug

#1262 [docs] Update Setup Notes
  doc/setup.md
Labels: documentation

#1264 [catnap] Don't Fail Silently When Cannot Set Socket Options
  src/rust/catnap/linux/transport.rs
Labels: bug

#1257 [libos] Add socket options
  examples/tcp-close/client.rs
  examples/tcp-close/main.rs
  examples/tcp-close/server.rs
  examples/tcp-echo/client.rs
  examples/tcp-echo/main.rs
  examples/tcp-echo/server.rs
  examples/tcp-wait/client.rs
  examples/tcp-wait/main.rs
  examples/tcp-wait/server.rs
  src/rust/catloop/socket.rs
  src/rust/catloop/transport.rs
  src/rust/catnap/linux/transport.rs
  src/rust/catnap/win/socket.rs
  src/rust/catnap/win/transport.rs
  src/rust/demikernel/bindings.rs
  src/rust/demikernel/libos/mod.rs
  src/rust/demikernel/libos/network/libos.rs
  src/rust/demikernel/libos/network/mod.rs
  src/rust/demikernel/libos/network/queue.rs
  src/rust/inetstack/mod.rs
  src/rust/inetstack/protocols/tcp/peer.rs
  src/rust/inetstack/protocols/tcp/socket.rs
  src/rust/lib.rs
  src/rust/pal/constants.rs
  src/rust/pal/data_structures.rs
  src/rust/runtime/network/socket/mod.rs
  src/rust/runtime/network/socket/option.rs
  src/rust/runtime/network/transport.rs
Labels: enhancement

#1268 [contrib] Updating Third-Party Dependencies
  Cargo.toml
  dpdk-rs/Cargo.toml
  nettest/Cargo.toml
Labels: enhancement

#1267 [pdpix] Expose System Calls for Setting / Getting Socket Options
  include/demi/libos.h
  tests/c/syscalls.c
Labels: enhancement

#1270 [libos] Disallow Setting SO_LINGER When Socket is Closing
  man/demi_getsockopt.md
  man/demi_setsockopt.md
  src/rust/demikernel/bindings.rs
  src/rust/demikernel/libos/network/queue.rs
  src/rust/runtime/network/socket/state.rs
Labels: bug

#1275 [build] Turn on Rust Log on Windows
  windows.mk
Labels: bug

#1276 [shim] Interpose `getsockopt()` and `setsockopt()`
  shim/src/ctrl/getsockopt.c
  shim/src/ctrl/setsockopt.c
Labels: enhancement

#1278 [catnapw] Enforce Close on ENOTCONN
  src/rust/catnap/win/transport.rs
Labels: bug

#1271 [pdpix] `getpeername()`
  include/demi/libos.h
  man/demi_getpeername.md
  shim/include/glue.h
  shim/src/ctrl/getpeername.c
  shim/src/glue.c
  src/rust/catloop/socket.rs
  src/rust/catloop/transport.rs
  src/rust/catnap/linux/transport.rs
  src/rust/catnap/win/socket.rs
  src/rust/catnap/win/transport.rs
  src/rust/catnap/win/winsock.rs
  src/rust/demikernel/bindings.rs
  src/rust/demikernel/libos/mod.rs
  src/rust/demikernel/libos/network/libos.rs
  src/rust/demikernel/libos/network/mod.rs
  src/rust/demikernel/libos/network/queue.rs
  src/rust/inetstack/mod.rs
  src/rust/inetstack/protocols/tcp/peer.rs
  src/rust/inetstack/protocols/tcp/socket.rs
  src/rust/pal/functions.rs
  src/rust/runtime/network/transport.rs
  tests/c/syscalls.c
Labels: feature

#1286 [bugfix] Workaround: Downgrade libc
  Cargo.toml
  nettest/Cargo.toml
Labels: bug

#1256 [test] Integration Tests Windows
  .github/workflows/catnapw.yml
  tests/rust/tcp-test/bind/mod.rs
  tests/rust/tcp-test/main.rs
Labels: enhancement

#1274 [libos] Merge Config Files
  doc/setup.md
  examples/tcp-close/client.rs
  examples/tcp-close/server.rs
  examples/tcp-echo/client.rs
  examples/tcp-echo/server.rs
  examples/tcp-wait/client.rs
  examples/tcp-wait/server.rs
  man/demi_getsockopt.md
  scripts/config/azure.yaml
  scripts/config/default.yaml
  shim/src/ctrl/getsockopt.c
  shim/src/ctrl/setsockopt.c
  src/rust/catloop/socket.rs
  src/rust/catloop/transport.rs
  src/rust/catnap/linux/transport.rs
  src/rust/catnap/win/config.rs
  src/rust/catnap/win/socket.rs
  src/rust/catnap/win/transport.rs
  src/rust/catnap/win/winsock.rs
  src/rust/catnip/runtime/mod.rs
  src/rust/catpowder/runtime/mod.rs
  src/rust/demikernel/bindings.rs
  src/rust/demikernel/config.rs
  src/rust/demikernel/libos/mod.rs
  src/rust/demikernel/libos/network/queue.rs
  src/rust/inetstack/mod.rs
  src/rust/inetstack/protocols/arp/tests.rs
  src/rust/inetstack/protocols/tcp/socket.rs
  src/rust/inetstack/protocols/tcp/tests/simulator.rs
  src/rust/inetstack/test_helpers/mod.rs
  src/rust/pal/data_structures.rs
  src/rust/runtime/network/config/arp.rs
  src/rust/runtime/network/socket/option.rs
  src/rust/runtime/network/types/macaddr.rs
  tests/rust/common/libos.rs
Labels: enhancement

#1288 [contrib] Updating Third Party Dependencies
  Cargo.toml
  dpdk-rs/Cargo.toml
  nettest/Cargo.toml
Labels: enhancement

#1281 [test] Test Sizes of C API
  linux.mk
  src/rust/runtime/types/memory.rs
  tests/c/linux.mk
  tests/c/sizes.c
  tests/c/windows.mk
  windows.mk
Labels: enhancement

#1293 [scripts] Script for Automating `config.yaml` Generation
  scripts/setup/config.ps1
  scripts/setup/config.sh
Labels: feature

#1258 [inetstack] Bug Fix: Support timed wait
  examples/tcp-close/client.rs
  examples/tcp-close/main.rs
  examples/tcp-close/server.rs
  examples/tcp-echo/client.rs
  examples/tcp-echo/main.rs
  examples/tcp-echo/server.rs
  examples/tcp-wait/client.rs
  examples/tcp-wait/main.rs
  examples/tcp-wait/server.rs
  src/rust/demikernel/config.rs
  src/rust/inetstack/protocols/tcp/active_open.rs
  src/rust/inetstack/protocols/tcp/constants.rs
  src/rust/inetstack/protocols/tcp/established/ctrlblk.rs
  src/rust/inetstack/protocols/tcp/established/mod.rs
  src/rust/inetstack/protocols/tcp/passive_open.rs
  src/rust/inetstack/protocols/tcp/peer.rs
  src/rust/inetstack/protocols/tcp/socket.rs
  src/rust/runtime/network/consts.rs
Labels: enhancement
