Repository microsoft/demikernel, pull requests merged in 2024-07, with the labels that each got.

#1319 [inetstack] Re-org
  src/rust/collections/hashttlcache.rs
  src/rust/collections/mod.rs
  src/rust/inetstack/collections/hashttlcache/mod.rs
  src/rust/inetstack/collections/hashttlcache/tests.rs
  src/rust/inetstack/collections/mod.rs
  src/rust/inetstack/mod.rs
  src/rust/inetstack/protocols/arp/cache/mod.rs
  src/rust/inetstack/protocols/mod.rs
  src/rust/inetstack/protocols/peer.rs
Labels: enhancement

#1323 [ci] Guard against posting comments for dev branch
  .github/workflows/catnap.yml
  .github/workflows/catnip.yml
  .github/workflows/catpowder.yml
Labels: enhancement

#1310 [catpowder] XDP LibOS
  .github/workflows/catnapw.yml
  Cargo.toml
  src/rust/catpowder/linux/mod.rs
  src/rust/catpowder/linux/rawsocket/mod.rs
  src/rust/catpowder/linux/rawsocket/rawsockaddr.rs
  src/rust/catpowder/linux/rawsocket/rawsocket.rs
  src/rust/catpowder/mod.rs
  src/rust/catpowder/win/api.rs
  src/rust/catpowder/win/mod.rs
  src/rust/catpowder/win/ring/buffer.rs
  src/rust/catpowder/win/ring/generic.rs
  src/rust/catpowder/win/ring/mod.rs
  src/rust/catpowder/win/ring/rule/mod.rs
  src/rust/catpowder/win/ring/rule/params.rs
  src/rust/catpowder/win/ring/rule/program.rs
  src/rust/catpowder/win/ring/rule/rule.rs
  src/rust/catpowder/win/ring/rx_ring.rs
  src/rust/catpowder/win/ring/tx_ring.rs
  src/rust/catpowder/win/ring/umemreg.rs
  src/rust/catpowder/win/runtime.rs
  src/rust/catpowder/win/socket.rs
  src/rust/demikernel/config.rs
  src/rust/demikernel/libos/mod.rs
  src/rust/demikernel/libos/network/mod.rs
  tools/ci/config/test/windows/catpowder.yaml
  tools/demikernel_ci.py
  windows.mk
  xdp-rs/Cargo.toml
  xdp-rs/build.rs
  xdp-rs/inlined.c
  xdp-rs/rust-toolchain
  xdp-rs/src/lib.rs
  xdp-rs/wrapper.h
Labels: feature

#1325 [shim] Optimizing epoll_wait
  include/demi/cc.h
  shim/include/glue.h
  shim/src/epoll.h
  shim/src/epoll/epoll.c
  shim/src/epoll/epoll_ctl.c
  shim/src/epoll/epoll_wait.c
  shim/src/glue.c
  shim/src/hashset.c
  shim/src/interpose.c
Labels: enhancement

#1333 [nettest] Initial Support for an Additional Protocol
  src/rust/inetstack/protocols/peer.rs
  src/rust/inetstack/protocols/tcp/tests/simulator.rs
  src/rust/inetstack/protocols/udp/mod.rs
Labels: enhancement

#1335 [nettest] Support UDP Protocol
  nettest/src/glue.rs
  nettest/src/grammar.y
  nettest/src/tokens.l
  src/rust/inetstack/protocols/tcp/tests/simulator.rs
Labels: feature

#1337 [ci] Automatically bootstrap VMs
  .github/workflows/catnip.yml
  .github/workflows/catpowder.yml
Labels: enhancement

#1338 [nettest] Adding UDP Test Cases
  nettest/input/tcp/accept/accept-blocking-1.pkt
  nettest/input/tcp/accept/accept-blocking-2.pkt
  nettest/input/tcp/accept/accept-refuse-1.pkt
  nettest/input/tcp/accept/accept-refuse-2.pkt
  nettest/input/tcp/accept/accept-refuse-3.pkt
  nettest/input/tcp/accept/accept-refuse-4.pkt
  nettest/input/tcp/accept/accept-refuse-5.pkt
  nettest/input/tcp/accept/accept-refuse-6.pkt
  nettest/input/tcp/accept/accept-syn-carrying-data.pkt
  nettest/input/tcp/close/close-blocking.pkt
  nettest/input/tcp/close/close-local.pkt
  nettest/input/tcp/close/close-remote.pkt
  nettest/input/tcp/close/close-simultaneous.pkt
  nettest/input/tcp/connect/connect-blocking.pkt
  nettest/input/tcp/connect/connect-early-reset.pkt
  nettest/input/tcp/connect/connect-refused.pkt
  nettest/input/tcp/pop/pop-blocking.pkt
  nettest/input/tcp/pop/pop-push-blocking.pkt
  nettest/input/tcp/push/push-blocking.pkt
  nettest/input/tcp/push/push-pop-blocking.pkt
  nettest/input/tcp/push/push-retransmission.pkt
  nettest/input/udp/pop-blocking-1.pkt
  nettest/input/udp/pop-blocking-2.pkt
  nettest/input/udp/push-blocking.pkt
  nettest/input/udp/push-pop-blocking-1.pkt
  nettest/input/udp/push-pop-blocking-2.pkt
  nettest/src/grammar.y
Labels: feature

#1343 [shim] Missing Initialization on Many Calls
  shim/src/interpose.c
Labels: bug

#1344 [contrib] Updating Dependencies
  Cargo.toml
  dpdk-rs/Cargo.toml
  nettest/Cargo.toml
  xdp-rs/Cargo.toml
Labels: enhancement

#1348 [build] Clean Dangling SHIM Artifact
  linux.mk
Labels: bug

#1349 [build] Missing Lib in LD_LIBRARY_PATH
  linux.mk
Labels: bug

#1350 [shim] Fix evaluation of conditional expression in epoll_create
  shim/src/interpose.c
Labels: bug
