Repository microsoft/demikernel, pull requests merged in 2024-08, with the labels that each got.

#1352 [build] Build SHIM Examples
  linux.mk
  shim/Makefile
Labels: enhancement

#1354 [contrib] Updating Third Party Dependencies
  Cargo.toml
  dpdk-rs/Cargo.toml
  dpdk-rs/src/lib.rs
  examples/pipe-open/main.rs
  examples/rust/tcp-dump.rs
  examples/rust/tcp-pktgen.rs
  examples/rust/udp-dump.rs
  examples/rust/udp-echo.rs
  examples/rust/udp-pktgen.rs
  examples/rust/udp-relay.rs
  examples/tcp-close/main.rs
  examples/tcp-echo/main.rs
  examples/tcp-wait/main.rs
  nettest/Cargo.toml
  rust-toolchain
  src/rust/lib.rs
  tests/rust/pipe-test/main.rs
  tests/rust/tcp-test/main.rs
  xdp-rs/Cargo.toml
  xdp-rs/rust-toolchain
  xdp-rs/src/lib.rs
Labels: enhancement

#1356 [shim] Race Condition In Initialization
  shim/src/interpose.c
Labels: bug

#1357 [shim] Use Direct Hash for FDs
  shim/src/queue.c
Labels: enhancement

#1358 [shim] Bad Initialization for `vfcntl()`, `epoll_ctl()`, `epoll_wait()` and `epoll_create()`
  shim/src/interpose.c
Labels: enhancement

#1359 [shim] Adding Condition Hints
  shim/src/epoll.h
  shim/src/interpose.c
  shim/src/utils.h
Labels: enhancement

#1361 [scripts] Typos in Config Script
  scripts/config/azure.yaml
  scripts/setup/config.sh
Labels: bug

#1355 [inetstack] Enhancement: Remove most clones
  src/rust/catnip/runtime/mod.rs
  src/rust/catpowder/linux/mod.rs
  src/rust/catpowder/win/runtime.rs
  src/rust/inetstack/protocols/arp/packet/message.rs
  src/rust/inetstack/protocols/arp/peer.rs
  src/rust/inetstack/protocols/arp/tests.rs
  src/rust/inetstack/protocols/icmpv4/datagram/message.rs
  src/rust/inetstack/protocols/icmpv4/peer.rs
  src/rust/inetstack/protocols/tcp/active_open.rs
  src/rust/inetstack/protocols/tcp/established/ctrlblk.rs
  src/rust/inetstack/protocols/tcp/passive_open.rs
  src/rust/inetstack/protocols/tcp/segment.rs
  src/rust/inetstack/protocols/tcp/tests/simulator.rs
  src/rust/inetstack/protocols/udp/datagram/mod.rs
  src/rust/inetstack/protocols/udp/socket.rs
  src/rust/inetstack/test_helpers/runtime.rs
  src/rust/runtime/network/mod.rs
  tests/rust/common/runtime.rs
Labels: enhancement

#1364 [ci] Support Running Redis with Catnip
  tools/ci/job/linux.py
  tools/ci/task/linux.py
  tools/demikernel_ci.py
Labels: enhancement

#1362 [ci] Run Redis in Catnip Pipeline
  .github/workflows/catnip.yml
Labels: enhancement

#1363 [runtime] Add return values to transmit and receive in the network runtime
  src/rust/catnip/runtime/mod.rs
  src/rust/catpowder/linux/mod.rs
  src/rust/catpowder/win/runtime.rs
  src/rust/inetstack/mod.rs
  src/rust/inetstack/protocols/arp/peer.rs
  src/rust/inetstack/protocols/icmpv4/peer.rs
  src/rust/inetstack/protocols/tcp/active_open.rs
  src/rust/inetstack/protocols/tcp/established/ctrlblk.rs
  src/rust/inetstack/protocols/tcp/passive_open.rs
  src/rust/inetstack/protocols/udp/socket.rs
  src/rust/inetstack/test_helpers/runtime.rs
  src/rust/runtime/network/mod.rs
  tests/rust/common/runtime.rs
Labels: enhancement

#1366 [catnip] Allow DPDK prepend function
  dpdk-rs/build.rs
  dpdk-rs/inlined.c
  dpdk-rs/src/lib.rs
Labels: enhancement

#1368 [runtime] Align DPDK and heap buffers for headroom
  src/rust/runtime/memory/demibuffer.rs
Labels: bug

#1370 [contrib] Updating Dependencies
  Cargo.toml
  dpdk-rs/Cargo.toml
  nettest/Cargo.toml
  xdp-rs/Cargo.toml
Labels: enhancement

#1369 [inetstack] Support prepend
  src/rust/catnip/runtime/memory/manager.rs
  src/rust/catnip/runtime/mod.rs
  src/rust/catpowder/linux/mod.rs
  src/rust/catpowder/win/runtime.rs
  src/rust/inetstack/protocols/arp/packet/message.rs
  src/rust/inetstack/protocols/arp/peer.rs
  src/rust/inetstack/protocols/arp/tests.rs
  src/rust/inetstack/protocols/icmpv4/datagram/message.rs
  src/rust/inetstack/protocols/icmpv4/peer.rs
  src/rust/inetstack/protocols/mod.rs
  src/rust/inetstack/protocols/tcp/active_open.rs
  src/rust/inetstack/protocols/tcp/established/ctrlblk.rs
  src/rust/inetstack/protocols/tcp/passive_open.rs
  src/rust/inetstack/protocols/tcp/segment.rs
  src/rust/inetstack/protocols/tcp/tests/simulator.rs
  src/rust/inetstack/protocols/udp/datagram/header.rs
  src/rust/inetstack/protocols/udp/datagram/mod.rs
  src/rust/inetstack/protocols/udp/mod.rs
  src/rust/inetstack/protocols/udp/socket.rs
  src/rust/inetstack/protocols/udp/tests.rs
  src/rust/inetstack/test_helpers/runtime.rs
  src/rust/runtime/network/mod.rs
  tests/rust/common/libos.rs
  tests/rust/common/runtime.rs
Labels: enhancement

#1373 [shim] Enhancement: Use demi_wait_any instead of demi_wait in shim ep…
  shim/src/epoll.h
  shim/src/epoll/epoll.c
  shim/src/epoll/epoll_wait.c
Labels: enhancement

#1378 [shim] Support `writev()`
  shim/src/data/send.c
Labels: feature

#1379 [inetstack] Move NetworkRuntime to Layer 1
  src/rust/catnip/runtime/mod.rs
  src/rust/catpowder/linux/mod.rs
  src/rust/catpowder/win/runtime.rs
  src/rust/demikernel/libos/mod.rs
  src/rust/inetstack/mod.rs
  src/rust/inetstack/protocols/arp/packet/message.rs
  src/rust/inetstack/protocols/arp/peer.rs
  src/rust/inetstack/protocols/arp/tests.rs
  src/rust/inetstack/protocols/icmpv4/datagram/message.rs
  src/rust/inetstack/protocols/icmpv4/peer.rs
  src/rust/inetstack/protocols/layer1/mod.rs
  src/rust/inetstack/protocols/layer1/packet.rs
  src/rust/inetstack/protocols/mod.rs
  src/rust/inetstack/protocols/peer.rs
  src/rust/inetstack/protocols/tcp/active_open.rs
  src/rust/inetstack/protocols/tcp/established/background/acknowledger.rs
  src/rust/inetstack/protocols/tcp/established/background/mod.rs
  src/rust/inetstack/protocols/tcp/established/background/retransmitter.rs
  src/rust/inetstack/protocols/tcp/established/background/sender.rs
  src/rust/inetstack/protocols/tcp/established/ctrlblk.rs
  src/rust/inetstack/protocols/tcp/established/mod.rs
  src/rust/inetstack/protocols/tcp/established/sender.rs
  src/rust/inetstack/protocols/tcp/passive_open.rs
  src/rust/inetstack/protocols/tcp/peer.rs
  src/rust/inetstack/protocols/tcp/segment.rs
  src/rust/inetstack/protocols/tcp/socket.rs
  src/rust/inetstack/protocols/tcp/tests/simulator.rs
  src/rust/inetstack/protocols/udp/datagram/mod.rs
  src/rust/inetstack/protocols/udp/peer.rs
  src/rust/inetstack/protocols/udp/socket.rs
  src/rust/inetstack/test_helpers/runtime.rs
  src/rust/runtime/network/mod.rs
  tests/rust/common/runtime.rs
Labels: enhancement
