Repository microsoft/demikernel, pull requests merged in 2024-04, with the labels that each got.

#1215 [contrib] Updating windows Crate
  Cargo.toml
  src/rust/catnap/win/error.rs
Labels: enhancement

#1217 [test] Windows Support for TCP Unit Tests
  tests/rust/tcp.rs
Labels: bug

#1218 [test] Multiplatform Errno in Simulator
  nettest/Cargo.toml
  nettest/input/connect-early-reset.pkt
  nettest/input/connect-timeout.pkt
  nettest/src/glue.rs
  nettest/src/grammar.y
  src/rust/inetstack/protocols/tcp/tests/simulator.rs
Labels: enhancement

#1221 [ci] Don't Allocate Zero-Length Buffer
  src/rust/runtime/memory/mod.rs
Labels: bug

#1223 [ci] Race Condition on TCP Integration tests
  tools/ci/job/factory.py
  tools/ci/job/linux.py
Labels: bug

#1224 [catnip] Disallow Zero-Length Buffer Allocation
  src/rust/catnip/runtime/memory/manager.rs
Labels: bug

#1222 [ci] Unit Tests for Windows
  tools/ci/job/factory.py
  tools/ci/job/generic.py
  tools/ci/job/linux.py
  tools/ci/job/windows.py
  tools/demikernel_ci.py
Labels: feature

#1225 [contrib] Updating Third Party Dependencies
  Cargo.toml
  dpdk-rs/Cargo.toml
Labels: enhancement

#1216 [runtime] Enhancement: add new demi_wait_next_n runtime binding
  include/demi/cc.h
  include/demi/libos.h
  include/demi/sga.h
  include/demi/types.h
  include/demi/wait.h
  src/rust/catmem/mod.rs
  src/rust/demikernel/bindings.rs
  src/rust/demikernel/libos/memory.rs
  src/rust/demikernel/libos/mod.rs
  src/rust/demikernel/libos/network/libos.rs
  src/rust/demikernel/libos/network/mod.rs
  src/rust/lib.rs
  src/rust/runtime/mod.rs
  tests/c/syscalls.c
Labels: enhancement

#1228 [ci] Report Perfance on NetworkLibOS
  tools/ci/job/utils.py
  tools/perf.py
Labels: enhancement

#1227 [runtime] Enhancement: Increase timer resolution
  src/rust/runtime/mod.rs
  tests/rust/tcp-test/connect/mod.rs
  tests/rust/tcp-test/listen/mod.rs
Labels: enhancement

#1230 [testing] Bug Fix: Add proper error checking
  tests/rust/tcp-test/accept/mod.rs
  tests/rust/tcp-test/wait/mod.rs
Labels: bug

#1229 [collections] Overflow on Buffer Copy
  src/rust/collections/concurrent_ring.rs
Labels: bug

#1232 [collections] Check for Invalid Push Size of Concurrent Ring Buffer
  src/rust/collections/concurrent_ring.rs
Labels: bug, enhancement

#1220 [demikernel] Bug Fix: Don't leak libos when calling init more than once
  man/demi_init.md
  src/rust/demikernel/bindings.rs
Labels: bug

#1234 [contrib] Updating Third-Party Dependnecies
  Cargo.toml
  dpdk-rs/Cargo.toml
  nettest/Cargo.toml
  rust-toolchain
Labels: enhancement

#1235 [ci] Get Root of Demikernel Repo
  tools/ci/git.py
Labels: bug

#1236 [pdpix] Demikernel in Thread Local Storage
  src/rust/demikernel/bindings.rs
Labels: enhancement

#1241 [build] Copy All Libs On Install
  linux.mk
Labels: bug

#1243 [ci] Integrate Redis to CI Infrastructure
  .github/workflows/catnap.yml
  shim/src/Makefile
  tools/ci/job/factory.py
  tools/ci/job/generic.py
  tools/ci/job/linux.py
  tools/ci/job/utils.py
  tools/ci/task/linux.py
  tools/demikernel_ci.py
Labels: enhancement

#1244 [inetstack] Bug Fix: Clamp window scale to 14
  src/rust/inetstack/protocols/tcp/active_open.rs
  src/rust/inetstack/protocols/tcp/constants.rs
  src/rust/runtime/network/consts.rs
Labels: bug

#1246 [testing] Turn timer tests back on
  src/rust/runtime/timer.rs
Labels: enhancement

#1247 [testing] Remove references to push2
  tests/rust/tcp.rs
Labels: enhancement

#1249 [catpowder] Close Raw Socket
  src/rust/catpowder/runtime/mod.rs
  src/rust/catpowder/runtime/rawsocket/rawsocket.rs
Labels: bug

#1253 [ci] Support Integration Tests for Windows
  .github/workflows/catloop.yml
  .github/workflows/catmem.yml
  .github/workflows/catnap.yml
  .github/workflows/catnip.yml
  .github/workflows/catpowder.yml
  tools/ci/job/factory.py
  tools/ci/job/windows.py
  tools/demikernel_ci.py
Labels: enhancement

#1254 [ci] Support System Tests in Windows
  tools/ci/config/test/catnapw.yaml
  tools/ci/job/factory.py
  tools/ci/job/windows.py
  tools/demikernel_ci.py
Labels: enhancement

#1250 [ci] Enable Unit Tests for Windows
  .github/workflows/catnapw.yml
Labels: enhancement

#1255 [test] Recursive Test Case Discovery
  linux.mk
  nettest/input/accept/accept-blocking-1.pkt
  nettest/input/accept/accept-blocking-2.pkt
  nettest/input/accept/accept-refuse-1.pkt
  nettest/input/accept/accept-refuse-2.pkt
  nettest/input/accept/accept-refuse-3.pkt
  nettest/input/accept/accept-refuse-4.pkt
  nettest/input/accept/accept-refuse-5.pkt
  nettest/input/accept/accept-refuse-6.pkt
  nettest/input/accept/accept-syn-carrying-data.pkt
  nettest/input/close/close-blocking.pkt
  nettest/input/close/close-local.pkt
  nettest/input/close/close-remote.pkt
  nettest/input/connect/connect-blocking.pkt
  nettest/input/connect/connect-early-reset.pkt
  nettest/input/connect/connect-timeout.pkt
  nettest/input/pop/pop-blocking.pkt
  nettest/input/pop/pop-push-blocking.pkt
  nettest/input/push/push-blocking.pkt
  nettest/input/push/push-pop-blocking.pkt
  nettest/input/push/push-retransmission.pkt
  src/rust/inetstack/protocols/tcp/tests/simulator.rs
  windows.mk
Labels: enhancement
