Repository microsoft/demikernel, pull requests merged in 2024-06, with the labels that each got.

#1291 [shim] Shim race conditions
  shim/include/glue.h
  shim/src/ctrl/getpeername.c
  shim/src/ctrl/getsockopt.c
  shim/src/ctrl/setsockopt.c
  shim/src/data/recv.c
  shim/src/data/send.c
  shim/src/glue.c
  shim/src/interpose.c
  shim/src/utils.h
Labels: bug

#1304 [inetstack] Properly close connecting sockets
  nettest/input/connect/connect-refused.pkt
  src/rust/inetstack/protocols/tcp/active_open.rs
  src/rust/inetstack/protocols/tcp/peer.rs
  src/rust/inetstack/protocols/tcp/socket.rs
  tools/demikernel_ci.py
Labels: bug

#1308 [contrib] Updating Dependencies
  Cargo.toml
  dpdk-rs/Cargo.toml
  examples/tcp-echo/client.rs
  nettest/Cargo.toml
Labels: enhancement

#1297 [profiler] Enhancement: Add C callback
  benchmarks/c/main.c
  examples/c/pipe-ping-pong.c
  examples/c/pipe-push-pop.c
  examples/c/tcp-ping-pong.c
  examples/c/tcp-push-pop.c
  examples/c/udp-ping-pong.c
  examples/c/udp-push-pop.c
  examples/pipe-open/main.rs
  examples/rust/pipe-ping-pong.rs
  examples/rust/pipe-push-pop.rs
  examples/rust/tcp-dump.rs
  examples/rust/tcp-ping-pong.rs
  examples/rust/tcp-pktgen.rs
  examples/rust/tcp-push-pop.rs
  examples/rust/udp-dump.rs
  examples/rust/udp-echo.rs
  examples/rust/udp-ping-pong.rs
  examples/rust/udp-pktgen.rs
  examples/rust/udp-push-pop.rs
  examples/rust/udp-relay.rs
  examples/tcp-close/main.rs
  examples/tcp-echo/main.rs
  examples/tcp-wait/main.rs
  include/demi/libos.h
  include/demi/types.h
  shim/include/glue.h
  shim/src/glue.c
  shim/src/init.c
  src/rust/demikernel/bindings.rs
  src/rust/demikernel/libos/mod.rs
  src/rust/perftools/profiler/mod.rs
  src/rust/perftools/profiler/scope.rs
  src/rust/runtime/types/mod.rs
  tests/c/sizes.c
  tests/c/syscalls.c
  tests/rust/pipe-test/create_pipe/mod.rs
  tests/rust/pipe-test/main.rs
  tests/rust/sga.rs
  tests/rust/tcp-test/main.rs
Labels: feature

#1315 [ci] Flamegraph and stack perf data
  .github/workflows/catnap.yml
  .github/workflows/catnip.yml
  .github/workflows/catpowder.yml
  src/rust/catnap/linux/transport.rs
  src/rust/catnap/win/overlapped.rs
  src/rust/catnap/win/transport.rs
  src/rust/demikernel/libos/network/libos.rs
  src/rust/inetstack/mod.rs
  src/rust/inetstack/protocols/arp/peer.rs
  src/rust/inetstack/protocols/icmpv4/peer.rs
  src/rust/inetstack/protocols/tcp/established/mod.rs
  src/rust/inetstack/protocols/tcp/passive_open.rs
  src/rust/perftools/profiler/mod.rs
  src/rust/perftools/profiler/scope.rs
  src/rust/runtime/mod.rs
  tools/perf.py
Labels: feature

#1317 [ci] Platform Switch Option
  .github/workflows/catloop.yml
  .github/workflows/catmem.yml
  .github/workflows/catnap.yml
  .github/workflows/catnapw.yml
  .github/workflows/catnip.yml
  .github/workflows/catpowder.yml
  tools/ci/config/test/catnapw.yaml
  tools/ci/config/test/linux/catloop.yaml
  tools/ci/config/test/linux/catmem.yaml
  tools/ci/config/test/linux/catnap.yaml
  tools/ci/config/test/linux/catnip.yaml
  tools/ci/config/test/linux/catpowder.yaml
  tools/ci/config/test/windows/catnap.yaml
  tools/ci/job/windows.py
  tools/demikernel_ci.py
Labels: enhancement
