Repository microsoft/demikernel, pull requests merged in 2025-04, with the labels that each got.

#1521 [network_simulator] Feature: Start sequence numbers at non-zero
  network_simulator/input/tcp/accept/accept-blocking-1.pkt
  network_simulator/input/tcp/accept/accept-duplicate-syn.pkt
  network_simulator/input/tcp/accept/accept-large-window-size.pkt
  network_simulator/input/tcp/accept/accept-refuse-1.pkt
  network_simulator/input/tcp/accept/accept-refuse-2.pkt
  network_simulator/input/tcp/accept/accept-refuse-3.pkt
  network_simulator/input/tcp/accept/accept-refuse-4.pkt
  network_simulator/input/tcp/accept/accept-refuse-5.pkt
  network_simulator/input/tcp/accept/accept-refuse-6.pkt
  network_simulator/input/tcp/accept/accept-syn-ack-retransmission.pkt
  network_simulator/input/tcp/accept/accept-syn-carrying-data.pkt
  network_simulator/input/tcp/close/close-blocking.pkt
  network_simulator/input/tcp/close/close-local-retransmission.pkt
  network_simulator/input/tcp/close/close-local.pkt
  network_simulator/input/tcp/close/close-out-of-order-fin.pkt
  network_simulator/input/tcp/close/close-remote-retransmission.pkt
  network_simulator/input/tcp/close/close-remote.pkt
  network_simulator/input/tcp/close/close-simultaneous.pkt
  network_simulator/input/tcp/connect/connect-blocking.pkt
  network_simulator/input/tcp/connect/connect-early-reset.pkt
  network_simulator/input/tcp/connect/connect-refused.pkt
  network_simulator/input/tcp/pop/pop-blocking.pkt
  network_simulator/input/tcp/pop/pop-push-blocking.pkt
  network_simulator/input/tcp/pop/pop-reordering.pkt
  network_simulator/input/tcp/pop/pop-retransmission.pkt
  network_simulator/input/tcp/push/push-blocking.pkt
  network_simulator/input/tcp/push/push-pop-blocking.pkt
  network_simulator/input/tcp/push/push-retransmission-2.pkt
  network_simulator/input/tcp/push/push-retransmission.pkt
  src/rust/inetstack/protocols/layer4/tcp/established/receiver.rs
  src/rust/inetstack/protocols/layer4/tcp/isn_generator.rs
  src/rust/inetstack/protocols/layer4/tcp/passive_open.rs
  src/rust/inetstack/test_helpers/engine.rs
Labels: feature

#1522 [catpowder] Enhancement: XDP refactor and bug fixes
  scripts/config/azure.yaml
  scripts/config/default.yaml
  src/rust/catpowder/win/cohosting.rs
  src/rust/catpowder/win/interface.rs
  src/rust/catpowder/win/mod.rs
  src/rust/catpowder/win/observability.rs
  src/rust/catpowder/win/ring/rx_ring.rs
  src/rust/catpowder/win/ring/tx_ring.rs
  src/rust/catpowder/win/ring/umemreg.rs
  src/rust/catpowder/win/rss.rs
  src/rust/catpowder/win/runtime.rs
  src/rust/demikernel/config.rs
  src/rust/runtime/mod.rs
Labels: bug, enhancement

#1534 [libos] Bug Fix: fix bug in send queue for pushto operations
  src/rust/demikernel/libos/network/libos.rs
  src/rust/demikernel/libos/network/queue.rs
Labels: bug

#1532 [script] Bug Fix: remove unnecessary pip install
  scripts/setup/debian.sh
Labels: bug
