Repository microsoft/demikernel, pull requests merged in 2025-05, with the labels that each got.

#1538 [inetstack] Bug Fix: Simultaneous close misses FIN resend
  network_simulator/input/tcp/close/close-local.pkt
  network_simulator/input/tcp/close/close-simultaneous.pkt
  src/rust/inetstack/protocols/layer4/tcp/established/mod.rs
  src/rust/inetstack/protocols/layer4/tcp/established/receiver.rs
  src/rust/inetstack/protocols/layer4/tcp/established/sender.rs
Labels: bug, confirmed

#1533 [bindings] Bug Fix: tweak and fix minor behavior in headers/bindings
  include/demi/cc.h
  include/demi/libos.h
  include/demi/types.h
  src/rust/demikernel/bindings.rs
Labels: bug

#1535 [bindings] Enhancement: add an optional logging callback to demi_args_t
  include/demi/types.h
  src/rust/demikernel/bindings.rs
  src/rust/runtime/logging.rs
  src/rust/runtime/types/mod.rs
  tests/c/sizes.c
Labels: enhancement

#1539 [config] Bug Fix: respect env var for MSS value
  linux.mk
  src/rust/demikernel/config.rs
  windows.mk
Labels: bug

#1548 [ci] Bug Fix: correct checkout sequence to get latest code
  tools/ci/task/linux.py
  tools/ci/task/windows.py
Labels: bug
